import { WorkIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'

export const AgiloftBlock: BlockConfig = {
  type: 'agiloft',
  name: 'Agiloft',
  description: 'Create, read, and manage records in Agiloft CLM',
  longDescription:
    'Integrate Agiloft Contract Lifecycle Management into your workflows. Create, read, update records, and run queries across any table.',
  docsLink: '#',
  category: 'tools',
  bgColor: '#001028',
  icon: WorkIcon,
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Create Record', id: 'agiloft_create_record' },
        { label: 'Read Record', id: 'agiloft_read_record' },
        { label: 'Update Record', id: 'agiloft_update_record' },
        { label: 'Delete Record', id: 'agiloft_delete_record' },
        { label: 'Query Records', id: 'agiloft_query_records' },
      ],
      required: true,
    },
    {
      id: 'instanceUrl',
      title: 'Instance URL',
      type: 'short-input',
      layout: 'full',
      placeholder: 'https://your-instance.agiloft.com',
      required: true,
    },
    {
      id: 'knowledgeBase',
      title: 'Knowledge Base',
      type: 'short-input',
      layout: 'half',
      placeholder: 'KB Name',
      required: true,
    },
    {
      id: 'login',
      title: 'Login',
      type: 'short-input',
      layout: 'half',
      placeholder: 'username',
      required: true,
    },
    {
      id: 'password',
      title: 'Password',
      type: 'short-input',
      layout: 'half',
      password: true,
      placeholder: 'password',
      required: true,
    },
    {
      id: 'table',
      title: 'Table',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Contract',
      required: true,
    },
    {
      id: 'recordId',
      title: 'Record ID',
      type: 'short-input',
      layout: 'full',
      placeholder: '12345',
      condition: {
        field: 'operation',
        value: ['agiloft_read_record', 'agiloft_update_record', 'agiloft_delete_record'],
      },
    },
    {
      id: 'data',
      title: 'Data (JSON)',
      type: 'long-input',
      layout: 'full',
      placeholder: '{"field": "value"}',
      condition: { field: 'operation', value: ['agiloft_create_record', 'agiloft_update_record'] },
    },
    {
      id: 'query',
      title: 'Query',
      type: 'short-input',
      layout: 'full',
      placeholder: 'status = "Active"',
      condition: { field: 'operation', value: ['agiloft_query_records'] },
    },
  ],
  tools: {
    access: [
      'agiloft_create_record',
      'agiloft_read_record',
      'agiloft_update_record',
      'agiloft_delete_record',
      'agiloft_query_records',
    ],
    config: {
      tool: (params) => params.operation || 'agiloft_create_record',
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    instanceUrl: { type: 'string', description: 'Instance URL' },
    knowledgeBase: { type: 'string', description: 'Knowledge base' },
    login: { type: 'string', description: 'Login' },
    password: { type: 'string', description: 'Password' },
    table: { type: 'string', description: 'Table name' },
    recordId: { type: 'string', description: 'Record ID' },
    data: { type: 'string', description: 'Record data JSON' },
    query: { type: 'string', description: 'Query string' },
  },
  outputs: {
    recordId: { type: 'string', description: 'Record ID' },
    data: { type: 'json', description: 'Record data' },
    records: { type: 'json', description: 'Query results' },
    recordCount: { type: 'number', description: 'Number of records' },
  },
}
