import { SearchIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'

export const AlgoliaBlock: BlockConfig = {
  type: 'algolia',
  name: 'Algolia',
  description: 'Search, index, and manage records in Algolia',
  longDescription:
    'Integrate Algolia search into your workflows. Perform full-text searches, add or update index records, and manage your search indices.',
  docsLink: '#',
  category: 'tools',
  bgColor: '#003DFF',
  icon: SearchIcon,
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Search', id: 'algolia_search' },
        { label: 'Add Record', id: 'algolia_index_document' },
        { label: 'Update Record', id: 'algolia_update_document' },
        { label: 'Delete Record', id: 'algolia_delete_document' },
        { label: 'Get Record', id: 'algolia_get_document' },
      ],
      required: true,
    },
    {
      id: 'appId',
      title: 'Application ID',
      type: 'short-input',
      layout: 'half',
      placeholder: 'XXXXXXXXXX',
      required: true,
    },
    {
      id: 'apiKey',
      title: 'API Key',
      type: 'short-input',
      layout: 'half',
      password: true,
      placeholder: 'Your Algolia API key',
      required: true,
    },
    {
      id: 'indexName',
      title: 'Index Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'my_index',
      required: true,
    },
    {
      id: 'query',
      title: 'Search Query',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Search term',
      condition: { field: 'operation', value: ['algolia_search'] },
    },
    {
      id: 'hitsPerPage',
      title: 'Results Per Page',
      type: 'short-input',
      layout: 'half',
      placeholder: '20',
      condition: { field: 'operation', value: ['algolia_search'] },
    },
    {
      id: 'filters',
      title: 'Filters',
      type: 'short-input',
      layout: 'half',
      placeholder: 'category:electronics',
      condition: { field: 'operation', value: ['algolia_search'] },
    },
    {
      id: 'objectId',
      title: 'Object ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'record-id',
      condition: {
        field: 'operation',
        value: ['algolia_update_document', 'algolia_delete_document', 'algolia_get_document'],
      },
    },
    {
      id: 'record',
      title: 'Record (JSON)',
      type: 'code',
      layout: 'full',
      placeholder: '{"name": "Product", "price": 29.99}',
      condition: {
        field: 'operation',
        value: ['algolia_index_document', 'algolia_update_document'],
      },
    },
  ],
  tools: {
    access: [
      'algolia_search',
      'algolia_index_document',
      'algolia_update_document',
      'algolia_delete_document',
      'algolia_get_document',
    ],
    config: {
      tool: (params) => params.operation || 'algolia_search',
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    appId: { type: 'string', description: 'Application ID' },
    apiKey: { type: 'string', description: 'API key' },
    indexName: { type: 'string', description: 'Index name' },
    query: { type: 'string', description: 'Search query' },
    hitsPerPage: { type: 'string', description: 'Results per page' },
    filters: { type: 'string', description: 'Search filters' },
    objectId: { type: 'string', description: 'Object ID' },
    record: { type: 'json', description: 'Record data' },
  },
  outputs: {
    hits: { type: 'json', description: 'Search results' },
    records: { type: 'json', description: 'Records' },
    nbHits: { type: 'number', description: 'Number of hits' },
  },
}
