import { DatabaseIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'

export const DynamoDBBlock: BlockConfig = {
  type: 'dynamodb',
  name: 'Amazon DynamoDB',
  description: 'Read, write, and query data in Amazon DynamoDB',
  longDescription:
    'Integrate Amazon DynamoDB into your workflows. Get, put, update, and delete items, plus scan and query tables and batch operations.',
  docsLink: '#',
  category: 'tools',
  bgColor: '#4D27A8',
  icon: DatabaseIcon,
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Get Item', id: 'dynamodb_get_item' },
        { label: 'Put Item', id: 'dynamodb_put_item' },
        { label: 'Update Item', id: 'dynamodb_update_item' },
        { label: 'Delete Item', id: 'dynamodb_delete_item' },
        { label: 'Query', id: 'dynamodb_query' },
        { label: 'Scan', id: 'dynamodb_scan' },
        { label: 'Batch Write', id: 'dynamodb_batch_write' },
      ],
      required: true,
    },
    {
      id: 'awsRegion',
      title: 'AWS Region',
      type: 'short-input',
      layout: 'half',
      placeholder: 'us-east-1',
      required: true,
    },
    {
      id: 'awsAccessKeyId',
      title: 'Access Key ID',
      type: 'short-input',
      layout: 'half',
      password: true,
      placeholder: 'AKIAIOSFODNN7EXAMPLE',
      required: true,
    },
    {
      id: 'awsSecretAccessKey',
      title: 'Secret Access Key',
      type: 'short-input',
      layout: 'full',
      password: true,
      placeholder: 'Secret access key',
      required: true,
    },
    {
      id: 'tableName',
      title: 'Table Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'MyTable',
      required: true,
    },
    {
      id: 'key',
      title: 'Primary Key (JSON)',
      type: 'code',
      layout: 'full',
      placeholder: '{"pk": "value", "sk": "sort_value"}',
      condition: {
        field: 'operation',
        value: ['dynamodb_get_item', 'dynamodb_update_item', 'dynamodb_delete_item'],
      },
    },
    {
      id: 'item',
      title: 'Item (JSON)',
      type: 'code',
      layout: 'full',
      placeholder: '{"pk": "value", "sk": "sort", "data": "content"}',
      condition: { field: 'operation', value: ['dynamodb_put_item'] },
    },
    {
      id: 'keyConditionExpression',
      title: 'Key Condition',
      type: 'short-input',
      layout: 'full',
      placeholder: 'pk = :pk',
      condition: { field: 'operation', value: ['dynamodb_query'] },
    },
    {
      id: 'filterExpression',
      title: 'Filter Expression',
      type: 'short-input',
      layout: 'full',
      placeholder: 'attribute = :val',
      condition: { field: 'operation', value: ['dynamodb_scan', 'dynamodb_query'] },
    },
  ],
  tools: {
    access: [
      'dynamodb_get_item',
      'dynamodb_put_item',
      'dynamodb_update_item',
      'dynamodb_delete_item',
      'dynamodb_query',
      'dynamodb_scan',
      'dynamodb_batch_write',
    ],
    config: {
      tool: (params) => params.operation || 'dynamodb_get_item',
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    awsRegion: { type: 'string', description: 'AWS region' },
    awsAccessKeyId: { type: 'string', description: 'AWS access key ID' },
    awsSecretAccessKey: { type: 'string', description: 'AWS secret access key' },
    tableName: { type: 'string', description: 'Table name' },
    key: { type: 'json', description: 'Primary key' },
    item: { type: 'json', description: 'Item data' },
    keyConditionExpression: { type: 'string', description: 'Key condition' },
    filterExpression: { type: 'string', description: 'Filter expression' },
  },
  outputs: {
    item: { type: 'json', description: 'Retrieved item' },
    items: { type: 'json', description: 'Query/scan results' },
    count: { type: 'number', description: 'Result count' },
  },
}
