import { SearchIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'

export const ElasticsearchBlock: BlockConfig = {
  type: 'elasticsearch',
  name: 'Elasticsearch',
  description: 'Search and manage data in Elasticsearch',
  longDescription:
    'Integrate Elasticsearch into your workflows. Search documents, index data, run aggregations, and manage indices.',
  docsLink: '#',
  category: 'tools',
  bgColor: '#005571',
  icon: SearchIcon,
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Search', id: 'elasticsearch_search' },
        { label: 'Index Document', id: 'elasticsearch_index' },
        { label: 'Get Document', id: 'elasticsearch_get' },
        { label: 'Delete Document', id: 'elasticsearch_delete' },
        { label: 'Bulk Index', id: 'elasticsearch_bulk' },
        { label: 'List Indices', id: 'elasticsearch_list_indices' },
      ],
      required: true,
    },
    {
      id: 'url',
      title: 'Elasticsearch URL',
      type: 'short-input',
      layout: 'full',
      placeholder: 'https://localhost:9200',
      required: true,
    },
    {
      id: 'apiKey',
      title: 'API Key',
      type: 'short-input',
      layout: 'full',
      password: true,
      placeholder: 'Your Elasticsearch API key',
    },
    {
      id: 'index',
      title: 'Index',
      type: 'short-input',
      layout: 'full',
      placeholder: 'my-index',
      required: true,
    },
    {
      id: 'query',
      title: 'Query (JSON)',
      type: 'code',
      layout: 'full',
      placeholder: '{"match": {"field": "value"}}',
      condition: { field: 'operation', value: ['elasticsearch_search'] },
    },
    {
      id: 'document',
      title: 'Document (JSON)',
      type: 'code',
      layout: 'full',
      placeholder: '{"field": "value"}',
      condition: { field: 'operation', value: ['elasticsearch_index'] },
    },
    {
      id: 'id',
      title: 'Document ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'doc-id',
      condition: { field: 'operation', value: ['elasticsearch_get', 'elasticsearch_delete'] },
    },
    {
      id: 'size',
      title: 'Max Results',
      type: 'short-input',
      layout: 'half',
      placeholder: '10',
      condition: { field: 'operation', value: ['elasticsearch_search'] },
    },
  ],
  tools: {
    access: [
      'elasticsearch_search',
      'elasticsearch_index',
      'elasticsearch_get',
      'elasticsearch_delete',
      'elasticsearch_bulk',
      'elasticsearch_list_indices',
    ],
    config: {
      tool: (params) => params.operation || 'elasticsearch_search',
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    url: { type: 'string', description: 'Elasticsearch URL' },
    apiKey: { type: 'string', description: 'API key' },
    index: { type: 'string', description: 'Index name' },
    query: { type: 'json', description: 'Search query' },
    document: { type: 'json', description: 'Document data' },
    id: { type: 'string', description: 'Document ID' },
    size: { type: 'string', description: 'Max results' },
  },
  outputs: {
    hits: { type: 'json', description: 'Search hits' },
    total: { type: 'number', description: 'Total results' },
    document: { type: 'json', description: 'Retrieved document' },
  },
}
