import { GitlabIcon } from '@/components/icons/gitlab-icon'
import type { BlockConfig } from '@/blocks/types'
import type { GitlabResponse } from '@/tools/gitlab/types'

export const GitlabBlock: BlockConfig<GitlabResponse> = {
  type: 'gitlab',
  name: 'GitLab',
  description:
    'Manage projects, issues, and files in GitLab, or trigger workflows from GitLab events',
  longDescription:
    'List and inspect projects, list and create issues, and read repository files through the GitLab API. Authenticate with a GitLab Personal Access Token. Trigger workflows from GitLab events like pushes, merge requests, issues, pipelines, and comments.',
  docsLink: '#',
  category: 'tools',
  bgColor: '#FC6D26',
  icon: GitlabIcon,
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'List projects', id: 'gitlab_list_projects' },
        { label: 'Get project', id: 'gitlab_get_project' },
        { label: 'List issues', id: 'gitlab_list_issues' },
        { label: 'Create issue', id: 'gitlab_create_issue' },
        { label: 'Get file', id: 'gitlab_get_file' },
      ],
      value: () => 'gitlab_list_projects',
    },
    {
      id: 'search',
      title: 'Search',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Project name',
      condition: { field: 'operation', value: 'gitlab_list_projects' },
    },
    {
      id: 'projectId',
      title: 'Project ID or Path',
      type: 'short-input',
      layout: 'full',
      placeholder: 'namespace/project or 12345',
      condition: {
        field: 'operation',
        value: [
          'gitlab_get_project',
          'gitlab_list_issues',
          'gitlab_create_issue',
          'gitlab_get_file',
        ],
      },
    },
    {
      id: 'state',
      title: 'State',
      type: 'short-input',
      layout: 'half',
      placeholder: 'opened, closed, all',
      condition: { field: 'operation', value: 'gitlab_list_issues' },
    },
    {
      id: 'labels',
      title: 'Labels',
      type: 'short-input',
      layout: 'half',
      placeholder: 'bug,urgent',
      condition: { field: 'operation', value: ['gitlab_list_issues', 'gitlab_create_issue'] },
    },
    {
      id: 'title',
      title: 'Title',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Issue title',
      condition: { field: 'operation', value: 'gitlab_create_issue' },
    },
    {
      id: 'description',
      title: 'Description',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Issue description (Markdown supported)',
      condition: { field: 'operation', value: 'gitlab_create_issue' },
    },
    {
      id: 'filePath',
      title: 'File Path',
      type: 'short-input',
      layout: 'half',
      placeholder: 'src/index.ts',
      condition: { field: 'operation', value: 'gitlab_get_file' },
    },
    {
      id: 'ref',
      title: 'Ref',
      type: 'short-input',
      layout: 'half',
      placeholder: 'main',
      condition: { field: 'operation', value: 'gitlab_get_file' },
    },
    {
      id: 'limit',
      title: 'Limit',
      type: 'short-input',
      layout: 'half',
      placeholder: '20',
      condition: { field: 'operation', value: 'gitlab_list_projects' },
    },
    {
      id: 'apiKey',
      title: 'GitLab Personal Access Token',
      type: 'short-input',
      layout: 'full',
      placeholder: 'glpat-...',
      password: true,
      required: true,
    },
    // TRIGGER MODE: Trigger configuration (only shown when trigger mode is active)
    {
      id: 'triggerConfig',
      title: 'Trigger Configuration',
      type: 'trigger-config',
      layout: 'full',
      triggerProvider: 'gitlab',
      availableTriggers: ['gitlab_webhook'],
    },
  ],
  tools: {
    access: [
      'gitlab_list_projects',
      'gitlab_get_project',
      'gitlab_list_issues',
      'gitlab_create_issue',
      'gitlab_get_file',
    ],
    config: {
      tool: (params) => params.operation || 'gitlab_list_projects',
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    apiKey: { type: 'string', description: 'GitLab Personal Access Token' },
    projectId: { type: 'string', description: 'Project ID or URL-encoded path' },
    search: { type: 'string', description: 'Search projects by name' },
    state: { type: 'string', description: 'Issue state filter' },
    labels: { type: 'string', description: 'Comma-separated label names' },
    title: { type: 'string', description: 'Issue title' },
    description: { type: 'string', description: 'Issue description' },
    filePath: { type: 'string', description: 'Path of the file in the repository' },
    ref: { type: 'string', description: 'Branch, tag, or commit' },
    limit: { type: 'number', description: 'Result limit' },
  },
  outputs: {
    data: { type: 'json', description: 'Result object or array from GitLab' },
    metadata: { type: 'json', description: 'Response metadata' },
    object_kind: {
      type: 'string',
      description: 'Event kind for trigger events (push, merge_request, issue, pipeline, note)',
    },
    object_attributes: {
      type: 'json',
      description: 'Changed object for merge request, issue, pipeline, and note events',
    },
    project: { type: 'json', description: 'Project the trigger event originated from' },
    commits: { type: 'json', description: 'Commits included in a push event' },
    branch: { type: 'string', description: 'Branch name extracted from ref' },
    action: { type: 'string', description: 'Action performed (e.g., open, merge, close)' },
  },
  triggers: {
    enabled: true,
    available: ['gitlab_webhook'],
  },
}
