import { JiraServiceManagementIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'

export const JiraServiceManagementBlock: BlockConfig = {
  type: 'jira_service_management',
  name: 'Jira Service Management',
  description: 'Manage service desks, requests, forms, and assets in Jira Service Management',
  longDescription:
    'Work with Jira Service Management across all three of its surfaces: the service desk (requests, queues, request types, transitions, SLAs, comments, participants, customers, organizations and approvals), JSM Forms, and Assets/CMDB. Authenticate once with your Jira account. Forms and Assets require the corresponding Atlassian products — Assets needs Jira Premium or above.',
  docsLink: '#',
  category: 'tools',
  bgColor: '#0052CC',
  icon: JiraServiceManagementIcon,
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      layout: 'full',
      options: [
        {
          label: 'Service desk: List Service Desks',
          id: 'jira_service_management_list_servicedesks',
        },
        { label: 'Service desk: Get Queues', id: 'jira_service_management_get_queues' },
        {
          label: 'Service desk: Get Request Types',
          id: 'jira_service_management_get_request_types',
        },
        {
          label: 'Service desk: Get Request Type Fields',
          id: 'jira_service_management_get_request_type_fields',
        },
        { label: 'Service desk: Create Request', id: 'jira_service_management_create_request' },
        { label: 'Service desk: Get Request', id: 'jira_service_management_get_request' },
        { label: 'Service desk: List Requests', id: 'jira_service_management_list_requests' },
        { label: 'Service desk: Get Transitions', id: 'jira_service_management_get_transitions' },
        {
          label: 'Service desk: Transition Request',
          id: 'jira_service_management_transition_request',
        },
        { label: 'Service desk: Get SLA', id: 'jira_service_management_get_sla' },
        { label: 'Comments & people: Add Comment', id: 'jira_service_management_add_comment' },
        { label: 'Comments & people: Get Comments', id: 'jira_service_management_get_comments' },
        {
          label: 'Comments & people: Add Participants',
          id: 'jira_service_management_add_participants',
        },
        {
          label: 'Comments & people: Get Participants',
          id: 'jira_service_management_get_participants',
        },
        { label: 'Customers & orgs: Add Customer', id: 'jira_service_management_add_customer' },
        { label: 'Customers & orgs: Get Customers', id: 'jira_service_management_get_customers' },
        {
          label: 'Customers & orgs: Create Organization',
          id: 'jira_service_management_create_organization',
        },
        {
          label: 'Customers & orgs: Add Organization',
          id: 'jira_service_management_add_organization',
        },
        {
          label: 'Customers & orgs: Get Organizations',
          id: 'jira_service_management_get_organizations',
        },
        { label: 'Approvals: Get Approvals', id: 'jira_service_management_get_approvals' },
        { label: 'Approvals: Answer Approval', id: 'jira_service_management_answer_approval' },
        { label: 'Forms: Get Form Templates', id: 'jira_service_management_get_form_templates' },
        { label: 'Forms: Get Issue Forms', id: 'jira_service_management_get_issue_forms' },
        { label: 'Forms: Attach Form', id: 'jira_service_management_attach_form' },
        { label: 'Forms: Get Form', id: 'jira_service_management_get_form' },
        { label: 'Forms: Get Form Structure', id: 'jira_service_management_get_form_structure' },
        { label: 'Forms: Get Form Answers', id: 'jira_service_management_get_form_answers' },
        { label: 'Forms: Save Form Answers', id: 'jira_service_management_save_form_answers' },
        { label: 'Forms: Submit Form', id: 'jira_service_management_submit_form' },
        { label: 'Forms: Reopen Form', id: 'jira_service_management_reopen_form' },
        { label: 'Forms: Copy Forms', id: 'jira_service_management_copy_forms' },
        { label: 'Forms: Delete Form', id: 'jira_service_management_delete_form' },
        { label: 'Forms: Externalise Form', id: 'jira_service_management_externalise_form' },
        { label: 'Forms: Internalise Form', id: 'jira_service_management_internalise_form' },
        { label: 'Assets: List Asset Schemas', id: 'jira_service_management_list_object_schemas' },
        { label: 'Assets: Get Asset Schema', id: 'jira_service_management_get_object_schema' },
        {
          label: 'Assets: List Asset Object Types',
          id: 'jira_service_management_list_object_types',
        },
        {
          label: 'Assets: Get Asset Object Type Attributes',
          id: 'jira_service_management_get_object_type_attributes',
        },
        { label: 'Assets: Search Assets (AQL)', id: 'jira_service_management_search_objects_aql' },
        { label: 'Assets: Create Asset Object', id: 'jira_service_management_create_object' },
        { label: 'Assets: Get Asset Object', id: 'jira_service_management_get_object' },
        { label: 'Assets: Update Asset Object', id: 'jira_service_management_update_object' },
        { label: 'Assets: Delete Asset Object', id: 'jira_service_management_delete_object' },
      ],
      value: () => 'jira_service_management_list_servicedesks',
    },
    {
      id: 'credential',
      title: 'Jira Account',
      type: 'oauth-input',
      layout: 'full',
      provider: 'jira',
      serviceId: 'jira',
      required: true,
    },
    {
      id: 'cloudId',
      title: 'Jira Cloud ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'e.g. 1324a887-45db-1bf4-1e99-ef0ff456d421',
      description: 'Find it at https://your-site.atlassian.net/_edge/tenant_info',
      required: true,
    },
    {
      id: 'accountIds',
      title: 'Account Ids',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: ['jira_service_management_add_customer', 'jira_service_management_add_participants'],
      },
    },
    {
      id: 'answers',
      title: 'Answers',
      type: 'long-input',
      layout: 'full',
      condition: { field: 'operation', value: 'jira_service_management_save_form_answers' },
    },
    {
      id: 'approvalId',
      title: 'Approval Id',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_answer_approval' },
    },
    {
      id: 'attributes',
      title: 'Attributes',
      type: 'long-input',
      layout: 'full',
      condition: {
        field: 'operation',
        value: ['jira_service_management_create_object', 'jira_service_management_update_object'],
      },
    },
    {
      id: 'body',
      title: 'Body',
      type: 'long-input',
      layout: 'full',
      condition: { field: 'operation', value: 'jira_service_management_add_comment' },
    },
    {
      id: 'comment',
      title: 'Comment',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_transition_request' },
    },
    {
      id: 'decision',
      title: 'Decision',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_answer_approval' },
    },
    {
      id: 'excludeAbstract',
      title: 'Exclude Abstract',
      type: 'switch',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_list_object_types' },
    },
    {
      id: 'expand',
      title: 'Expand',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: [
          'jira_service_management_get_comments',
          'jira_service_management_get_request',
          'jira_service_management_get_request_types',
        ],
      },
    },
    {
      id: 'formId',
      title: 'Form Id',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: [
          'jira_service_management_delete_form',
          'jira_service_management_externalise_form',
          'jira_service_management_get_form',
          'jira_service_management_get_form_answers',
          'jira_service_management_get_form_structure',
          'jira_service_management_internalise_form',
          'jira_service_management_reopen_form',
          'jira_service_management_save_form_answers',
          'jira_service_management_submit_form',
        ],
      },
    },
    {
      id: 'formIds',
      title: 'Form Ids',
      type: 'long-input',
      layout: 'full',
      condition: { field: 'operation', value: 'jira_service_management_copy_forms' },
    },
    {
      id: 'formTemplateId',
      title: 'Form Template Id',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_attach_form' },
    },
    {
      id: 'groupId',
      title: 'Group Id',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_get_request_types' },
    },
    {
      id: 'includeAttributes',
      title: 'Include Attributes',
      type: 'switch',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_search_objects_aql' },
    },
    {
      id: 'includeCount',
      title: 'Include Count',
      type: 'switch',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_get_queues' },
    },
    {
      id: 'includeCounts',
      title: 'Include Counts',
      type: 'switch',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_list_object_schemas' },
    },
    {
      id: 'internal',
      title: 'Internal',
      type: 'switch',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_get_comments' },
    },
    {
      id: 'isPublic',
      title: 'Is Public',
      type: 'switch',
      layout: 'half',
      condition: {
        field: 'operation',
        value: ['jira_service_management_add_comment', 'jira_service_management_get_comments'],
      },
    },
    {
      id: 'issueIdOrKey',
      title: 'Issue Id Or Key',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: [
          'jira_service_management_add_comment',
          'jira_service_management_add_participants',
          'jira_service_management_answer_approval',
          'jira_service_management_attach_form',
          'jira_service_management_delete_form',
          'jira_service_management_externalise_form',
          'jira_service_management_get_approvals',
          'jira_service_management_get_comments',
          'jira_service_management_get_form',
          'jira_service_management_get_form_answers',
          'jira_service_management_get_issue_forms',
          'jira_service_management_get_participants',
          'jira_service_management_get_request',
          'jira_service_management_get_sla',
          'jira_service_management_get_transitions',
          'jira_service_management_internalise_form',
          'jira_service_management_reopen_form',
          'jira_service_management_save_form_answers',
          'jira_service_management_submit_form',
          'jira_service_management_transition_request',
        ],
      },
    },
    {
      id: 'limit',
      title: 'Limit',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: [
          'jira_service_management_get_approvals',
          'jira_service_management_get_comments',
          'jira_service_management_get_customers',
          'jira_service_management_get_organizations',
          'jira_service_management_get_participants',
          'jira_service_management_get_queues',
          'jira_service_management_get_request_types',
          'jira_service_management_get_sla',
          'jira_service_management_get_transitions',
          'jira_service_management_list_requests',
          'jira_service_management_list_servicedesks',
        ],
      },
    },
    {
      id: 'maxResults',
      title: 'Max Results',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_list_object_schemas' },
    },
    {
      id: 'name',
      title: 'Name',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_create_organization' },
    },
    {
      id: 'objectId',
      title: 'Object Id',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: [
          'jira_service_management_delete_object',
          'jira_service_management_get_object',
          'jira_service_management_update_object',
        ],
      },
    },
    {
      id: 'objectSchemaId',
      title: 'Object Schema Id',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_search_objects_aql' },
    },
    {
      id: 'objectTypeId',
      title: 'Object Type Id',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: [
          'jira_service_management_create_object',
          'jira_service_management_get_object_type_attributes',
          'jira_service_management_search_objects_aql',
          'jira_service_management_update_object',
        ],
      },
    },
    {
      id: 'onlyValueEditable',
      title: 'Only Value Editable',
      type: 'switch',
      layout: 'half',
      condition: {
        field: 'operation',
        value: 'jira_service_management_get_object_type_attributes',
      },
    },
    {
      id: 'organizationId',
      title: 'Organization Id',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_add_organization' },
    },
    {
      id: 'page',
      title: 'Page',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_search_objects_aql' },
    },
    {
      id: 'projectIdOrKey',
      title: 'Project Id Or Key',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: [
          'jira_service_management_get_form_structure',
          'jira_service_management_get_form_templates',
        ],
      },
    },
    {
      id: 'qlQuery',
      title: 'Ql Query',
      type: 'long-input',
      layout: 'full',
      condition: { field: 'operation', value: 'jira_service_management_search_objects_aql' },
    },
    {
      id: 'query',
      title: 'Query',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: [
          'jira_service_management_get_customers',
          'jira_service_management_get_object_type_attributes',
        ],
      },
    },
    {
      id: 'requestFieldValues',
      title: 'Request Field Values',
      type: 'long-input',
      layout: 'full',
      condition: { field: 'operation', value: 'jira_service_management_create_request' },
    },
    {
      id: 'requestOwnership',
      title: 'Request Ownership',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_list_requests' },
    },
    {
      id: 'requestStatus',
      title: 'Request Status',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_list_requests' },
    },
    {
      id: 'requestTypeId',
      title: 'Request Type Id',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: [
          'jira_service_management_create_request',
          'jira_service_management_get_request_type_fields',
        ],
      },
    },
    {
      id: 'resultsPerPage',
      title: 'Results Per Page',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_search_objects_aql' },
    },
    {
      id: 'schemaId',
      title: 'Schema Id',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: [
          'jira_service_management_get_object_schema',
          'jira_service_management_list_object_types',
        ],
      },
    },
    {
      id: 'searchQuery',
      title: 'Search Query',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_get_request_types' },
    },
    {
      id: 'searchTerm',
      title: 'Search Term',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_list_requests' },
    },
    {
      id: 'serviceDeskId',
      title: 'Service Desk Id',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: [
          'jira_service_management_add_customer',
          'jira_service_management_add_organization',
          'jira_service_management_create_request',
          'jira_service_management_get_customers',
          'jira_service_management_get_organizations',
          'jira_service_management_get_queues',
          'jira_service_management_get_request_type_fields',
          'jira_service_management_get_request_types',
          'jira_service_management_list_requests',
        ],
      },
    },
    {
      id: 'sourceIssueIdOrKey',
      title: 'Source Issue Id Or Key',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_copy_forms' },
    },
    {
      id: 'start',
      title: 'Start',
      type: 'short-input',
      layout: 'half',
      condition: {
        field: 'operation',
        value: [
          'jira_service_management_get_approvals',
          'jira_service_management_get_comments',
          'jira_service_management_get_customers',
          'jira_service_management_get_organizations',
          'jira_service_management_get_participants',
          'jira_service_management_get_queues',
          'jira_service_management_get_request_types',
          'jira_service_management_get_sla',
          'jira_service_management_get_transitions',
          'jira_service_management_list_requests',
          'jira_service_management_list_servicedesks',
        ],
      },
    },
    {
      id: 'startAt',
      title: 'Start At',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_list_object_schemas' },
    },
    {
      id: 'targetIssueIdOrKey',
      title: 'Target Issue Id Or Key',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_copy_forms' },
    },
    {
      id: 'transitionId',
      title: 'Transition Id',
      type: 'short-input',
      layout: 'half',
      condition: { field: 'operation', value: 'jira_service_management_transition_request' },
    },
    // TRIGGER MODE: Trigger configuration (only shown when trigger mode is active)
    {
      id: 'triggerConfig',
      title: 'Trigger Configuration',
      type: 'trigger-config',
      layout: 'full',
      triggerProvider: 'jira_service_management',
      availableTriggers: ['jira_service_management_webhook'],
    },
  ],
  tools: {
    access: [
      'jira_service_management_add_comment',
      'jira_service_management_add_customer',
      'jira_service_management_add_organization',
      'jira_service_management_add_participants',
      'jira_service_management_answer_approval',
      'jira_service_management_attach_form',
      'jira_service_management_copy_forms',
      'jira_service_management_create_object',
      'jira_service_management_create_organization',
      'jira_service_management_create_request',
      'jira_service_management_delete_form',
      'jira_service_management_delete_object',
      'jira_service_management_externalise_form',
      'jira_service_management_get_approvals',
      'jira_service_management_get_comments',
      'jira_service_management_get_customers',
      'jira_service_management_get_form',
      'jira_service_management_get_form_answers',
      'jira_service_management_get_form_structure',
      'jira_service_management_get_form_templates',
      'jira_service_management_get_issue_forms',
      'jira_service_management_get_object',
      'jira_service_management_get_object_schema',
      'jira_service_management_get_object_type_attributes',
      'jira_service_management_get_organizations',
      'jira_service_management_get_participants',
      'jira_service_management_get_queues',
      'jira_service_management_get_request',
      'jira_service_management_get_request_type_fields',
      'jira_service_management_get_request_types',
      'jira_service_management_get_sla',
      'jira_service_management_get_transitions',
      'jira_service_management_internalise_form',
      'jira_service_management_list_object_schemas',
      'jira_service_management_list_object_types',
      'jira_service_management_list_requests',
      'jira_service_management_list_servicedesks',
      'jira_service_management_reopen_form',
      'jira_service_management_save_form_answers',
      'jira_service_management_search_objects_aql',
      'jira_service_management_submit_form',
      'jira_service_management_transition_request',
      'jira_service_management_update_object',
    ],
    config: {
      tool: (params) => params.operation || 'jira_service_management_list_servicedesks',
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    cloudId: { type: 'string', description: 'Jira Cloud ID' },
    accountIds: {
      type: 'string',
      description: 'Comma-separated Atlassian account IDs to add as customers',
    },
    answers: { type: 'json', description: '' },
    approvalId: { type: 'string', description: 'Approval ID to answer' },
    attributes: { type: 'json', description: '' },
    body: { type: 'string', description: 'Comment body text' },
    comment: { type: 'string', description: 'Optional comment to add during transition' },
    decision: { type: 'string', description: 'Decision: "approve" or "decline"' },
    excludeAbstract: {
      type: 'boolean',
      description: 'Exclude abstract object types from the result',
    },
    expand: {
      type: 'string',
      description: 'Comma-separated fields to expand: renderedBody, attachment',
    },
    formId: { type: 'string', description: 'Form instance UUID to delete' },
    formIds: { type: 'json', description: '' },
    formTemplateId: { type: 'string', description: 'Form template UUID (from Get Form Templates)' },
    groupId: { type: 'string', description: 'Filter by request type group ID' },
    includeAttributes: {
      type: 'boolean',
      description: 'Include resolved attribute values on each object (defaults to true)',
    },
    includeCount: {
      type: 'boolean',
      description: 'Include issue count for each queue (true/false)',
    },
    includeCounts: {
      type: 'boolean',
      description: 'Include object and object-type counts per schema',
    },
    internal: { type: 'boolean', description: 'Filter to only internal comments (true/false)' },
    isPublic: {
      type: 'boolean',
      description: 'Whether the comment is public (visible to customer) or internal (true/false)',
    },
    issueIdOrKey: { type: 'string', description: 'Issue ID or key (e.g., SD-123)' },
    limit: { type: 'number', description: 'Maximum results to return (e.g., 10, 25, 50)' },
    maxResults: { type: 'number', description: 'Maximum schemas to return (e.g., 25, 50)' },
    name: { type: 'string', description: 'Name of the organization to create' },
    objectId: { type: 'string', description: 'The Assets object ID to delete' },
    objectSchemaId: {
      type: 'string',
      description: 'Optionally scope the search to a single object schema ID',
    },
    objectTypeId: { type: 'string', description: 'The object type ID to create the object under' },
    onlyValueEditable: {
      type: 'boolean',
      description: 'Return only attributes whose values can be edited',
    },
    organizationId: { type: 'string', description: 'Organization ID to add to the service desk' },
    page: { type: 'number', description: 'Page number (1-based, defaults to 1)' },
    projectIdOrKey: {
      type: 'string',
      description: 'Jira project ID or key (e.g., "10001" or "SD")',
    },
    qlQuery: {
      type: 'string',
      description: 'AQL query string (e.g., objectType = "Host" AND "Operating System" = "Ubuntu")',
    },
    query: {
      type: 'string',
      description: 'Search query to filter customers (e.g., "john", "acme")',
    },
    requestFieldValues: { type: 'json', description: '' },
    requestOwnership: {
      type: 'string',
      description: 'Filter by ownership (OWNED_REQUESTS, PARTICIPATED_REQUESTS, ALL_REQUESTS)',
    },
    requestStatus: {
      type: 'string',
      description: 'Filter by status (OPEN_REQUESTS, CLOSED_REQUESTS, ALL_REQUESTS)',
    },
    requestTypeId: { type: 'string', description: 'ID of the request type' },
    resultsPerPage: { type: 'number', description: 'Results per page (e.g., 25, 50)' },
    schemaId: { type: 'string', description: 'The Assets object schema ID' },
    searchQuery: { type: 'string', description: 'Filter request types by name' },
    searchTerm: { type: 'string', description: 'Filter requests by summary text' },
    serviceDeskId: { type: 'string', description: 'Service Desk ID (e.g., "1", "2")' },
    sourceIssueIdOrKey: {
      type: 'string',
      description: 'Source issue ID or key to copy forms from (e.g., "SD-123")',
    },
    start: { type: 'number', description: 'Start index for pagination (e.g., 0, 50, 100)' },
    startAt: { type: 'number', description: 'Pagination start index (e.g., 0, 50)' },
    targetIssueIdOrKey: {
      type: 'string',
      description: 'Target issue ID or key to copy forms to (e.g., "SD-456")',
    },
    transitionId: { type: 'string', description: 'Transition ID to apply' },
  },
  outputs: {
    data: { type: 'json', description: 'Result payload from Jira Service Management' },
    metadata: { type: 'json', description: 'Response metadata' },
    event_type: { type: 'string', description: 'Jira event (trigger mode)' },
    issue_key: { type: 'string', description: 'Issue key, e.g. SUP-123' },
    summary: { type: 'string', description: 'Request summary' },
    status: { type: 'string', description: 'Current status name' },
    reporter_email: { type: 'string', description: 'Reporter email address' },
    comment_body: { type: 'string', description: 'Comment text (comment events)' },
  },
  triggers: {
    enabled: true,
    available: ['jira_service_management_webhook'],
  },
}
