import { OktaIcon } from '@/components/icons/okta-icon'
import type { BlockConfig } from '@/blocks/types'
import type { OktaResponse } from '@/tools/okta/types'

export const OktaBlock: BlockConfig<OktaResponse> = {
  type: 'okta',
  name: 'Okta',
  description: 'Manage users and groups in your Okta organization',
  longDescription:
    'List and retrieve users, create new users, and list groups through the Okta Management API. Authenticate with your Okta org URL and an API token.',
  docsLink: '#',
  category: 'tools',
  bgColor: '#007DC1',
  icon: OktaIcon,
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'List users', id: 'okta_list_users' },
        { label: 'Get user', id: 'okta_get_user' },
        { label: 'Create user', id: 'okta_create_user' },
        { label: 'List groups', id: 'okta_list_groups' },
      ],
      value: () => 'okta_list_users',
    },
    {
      id: 'userId',
      title: 'User ID or Login',
      type: 'short-input',
      layout: 'full',
      placeholder: '00u1a2b3c4d5e6f7g8h9 or user@example.com',
      condition: { field: 'operation', value: 'okta_get_user' },
    },
    {
      id: 'firstName',
      title: 'First Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Jane',
      condition: { field: 'operation', value: 'okta_create_user' },
    },
    {
      id: 'lastName',
      title: 'Last Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Doe',
      condition: { field: 'operation', value: 'okta_create_user' },
    },
    {
      id: 'email',
      title: 'Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'jane.doe@example.com',
      condition: { field: 'operation', value: 'okta_create_user' },
    },
    {
      id: 'login',
      title: 'Login',
      type: 'short-input',
      layout: 'half',
      placeholder: 'jane.doe@example.com',
      condition: { field: 'operation', value: 'okta_create_user' },
    },
    {
      id: 'search',
      title: 'Search',
      type: 'short-input',
      layout: 'full',
      placeholder: 'profile.email co "example.com"',
      condition: { field: 'operation', value: ['okta_list_users', 'okta_list_groups'] },
    },
    {
      id: 'limit',
      title: 'Limit',
      type: 'short-input',
      layout: 'half',
      placeholder: '50',
      condition: { field: 'operation', value: ['okta_list_users', 'okta_list_groups'] },
    },
    {
      id: 'orgUrl',
      title: 'Org URL',
      type: 'short-input',
      layout: 'full',
      placeholder: 'https://your-org.okta.com',
      required: true,
    },
    {
      id: 'apiToken',
      title: 'API Token',
      type: 'short-input',
      layout: 'full',
      password: true,
      required: true,
    },
  ],
  tools: {
    access: ['okta_list_users', 'okta_get_user', 'okta_create_user', 'okta_list_groups'],
    config: {
      tool: (params) => params.operation || 'okta_list_users',
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    orgUrl: { type: 'string', description: 'Okta org URL' },
    apiToken: { type: 'string', description: 'Okta API token' },
    userId: { type: 'string', description: 'User ID or login' },
    firstName: { type: 'string', description: 'First name' },
    lastName: { type: 'string', description: 'Last name' },
    email: { type: 'string', description: 'Email address' },
    login: { type: 'string', description: 'Login' },
    search: { type: 'string', description: 'Search expression' },
    limit: { type: 'number', description: 'Result limit' },
  },
  outputs: {
    data: { type: 'json', description: 'Result object or array from Okta' },
    metadata: { type: 'json', description: 'Response metadata' },
  },
}
