import { SMTPIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'
import type { SMTPResponse } from '@/tools/smtp/types'

export const SMTPBlock: BlockConfig<SMTPResponse> = {
  type: 'smtp',
  name: 'SMTP Email',
  description: 'Send emails via any SMTP server',
  longDescription:
    'Send emails through any SMTP server including Gmail, Outlook/Office 365, Yahoo, Amazon SES, SendGrid, Mailgun, or your own custom SMTP server. Uses standard SMTP protocol with STARTTLS/SSL support — no OAuth required, just provide your SMTP credentials.',
  docsLink: '#',
  category: 'tools',
  bgColor: '#FB923C',
  icon: SMTPIcon,
  subBlocks: [
    // ── SMTP Server Configuration ──
    {
      id: 'host',
      title: 'SMTP Host',
      type: 'short-input',
      layout: 'half',
      placeholder: 'smtp.gmail.com',
      required: true,
      description: 'SMTP server hostname',
    },
    {
      id: 'port',
      title: 'Port',
      type: 'short-input',
      layout: 'half',
      placeholder: '587',
      value: () => '587',
      description: 'SMTP port (587 for STARTTLS, 465 for SSL)',
    },
    {
      id: 'username',
      title: 'Username',
      type: 'short-input',
      layout: 'half',
      placeholder: 'your-email@example.com',
      required: true,
      description: 'SMTP login username (usually your email)',
    },
    {
      id: 'password',
      title: 'Password',
      type: 'short-input',
      layout: 'half',
      placeholder: 'App password or SMTP password',
      password: true,
      required: true,
      description: 'SMTP password or app-specific password',
    },
    {
      id: 'secure',
      title: 'Use SSL/TLS',
      type: 'switch',
      layout: 'half',
      description: 'Enable for port 465 (SSL). Leave off for port 587 (STARTTLS)',
    },
    // ── Email Fields ──
    {
      id: 'to',
      title: 'To',
      type: 'short-input',
      layout: 'full',
      placeholder: 'recipient@example.com',
      required: true,
      description: 'Recipient email addresses (comma-separated for multiple)',
    },
    {
      id: 'subject',
      title: 'Subject',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Email subject',
      required: true,
    },
    {
      id: 'body',
      title: 'Body',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Email content...',
      required: true,
    },
    {
      id: 'isHtml',
      title: 'Send as HTML',
      type: 'switch',
      layout: 'half',
      description: 'Treat the body as HTML content',
    },
    // ── Advanced Settings ──
    {
      id: 'from',
      title: 'From Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'sender@example.com (defaults to username)',
      mode: 'advanced',
      description: 'Override sender email address',
    },
    {
      id: 'fromName',
      title: 'From Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'John Doe',
      mode: 'advanced',
      description: 'Sender display name',
    },
    {
      id: 'cc',
      title: 'CC',
      type: 'short-input',
      layout: 'full',
      placeholder: 'CC recipients (comma-separated)',
      mode: 'advanced',
      required: false,
    },
    {
      id: 'bcc',
      title: 'BCC',
      type: 'short-input',
      layout: 'full',
      placeholder: 'BCC recipients (comma-separated)',
      mode: 'advanced',
      required: false,
    },
    {
      id: 'replyTo',
      title: 'Reply-To',
      type: 'short-input',
      layout: 'full',
      placeholder: 'reply-to@example.com',
      mode: 'advanced',
      required: false,
      description: 'Reply-to email address (if different from sender)',
    },
  ],
  tools: {
    access: ['smtp_send'],
  },
  inputs: {
    // SMTP server config
    host: { type: 'string', description: 'SMTP server hostname' },
    port: { type: 'number', description: 'SMTP server port' },
    username: { type: 'string', description: 'SMTP username' },
    password: { type: 'string', description: 'SMTP password' },
    secure: { type: 'boolean', description: 'Use SSL/TLS connection' },
    // Email fields
    to: { type: 'string', description: 'Recipient email addresses' },
    subject: { type: 'string', description: 'Email subject' },
    body: { type: 'string', description: 'Email body content' },
    isHtml: { type: 'boolean', description: 'Send body as HTML' },
    // Advanced
    from: { type: 'string', description: 'Sender email address' },
    fromName: { type: 'string', description: 'Sender display name' },
    cc: { type: 'string', description: 'CC recipients' },
    bcc: { type: 'string', description: 'BCC recipients' },
    replyTo: { type: 'string', description: 'Reply-to email address' },
  },
  outputs: {
    messageId: { type: 'string', description: 'Message ID from the SMTP server' },
    accepted: { type: 'json', description: 'List of accepted recipient addresses' },
    rejected: { type: 'json', description: 'List of rejected recipient addresses' },
    status: { type: 'string', description: 'SMTP server response status' },
    error: { type: 'string', description: 'Error message if sending failed' },
  },
}
