import { StagehandIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'
import type { StagehandAgentResponse } from '@/tools/stagehand/types'

export const StagehandAgentBlock: BlockConfig<StagehandAgentResponse> = {
  type: 'stagehand_agent',
  name: 'Stagehand Agent',
  description: 'Autonomous web browsing agent',
  longDescription:
    'Use Stagehand to create an autonomous web browsing agent that can navigate across websites, perform tasks, and return structured data.',
  docsLink: '#',
  category: 'tools',
  bgColor: '#FFC83C',
  icon: StagehandIcon,
  subBlocks: [
    {
      id: 'startUrl',
      title: 'Starting URL',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter the starting URL for the agent',
      required: true,
    },
    {
      id: 'task',
      title: 'Task',
      type: 'long-input',
      layout: 'full',
      placeholder:
        'Enter the task or goal for the agent to achieve. Reference variables using %key% syntax.',
      required: true,
    },
    {
      id: 'provider',
      title: 'Provider',
      type: 'dropdown',
      layout: 'half',
      options: [
        { label: 'Anthropic', id: 'anthropic' },
        { label: 'OpenAI', id: 'openai' },
        { label: 'Google', id: 'google' },
      ],
      value: () => 'anthropic',
    },
    {
      id: 'model',
      title: 'Model',
      type: 'dropdown',
      layout: 'half',
      options: [
        { label: 'anthropic/claude-sonnet-4-5', id: 'anthropic/claude-sonnet-4-5' },
        { label: 'anthropic/claude-sonnet-4', id: 'anthropic/claude-sonnet-4' },
        { label: 'openai/gpt-4o', id: 'openai/gpt-4o' },
        { label: 'openai/gpt-4.1', id: 'openai/gpt-4.1' },
        {
          label: 'google/gemini-2.5-pro-preview-03-25',
          id: 'google/gemini-2.5-pro-preview-03-25',
        },
      ],
      value: () => 'anthropic/claude-sonnet-4-5',
    },
    {
      id: 'mode',
      title: 'Agent Mode',
      type: 'dropdown',
      layout: 'half',
      options: [
        { label: 'Hybrid', id: 'hybrid' },
        { label: 'DOM', id: 'dom' },
        { label: 'CUA', id: 'cua' },
      ],
      value: () => 'hybrid',
    },
    {
      id: 'maxSteps',
      title: 'Max Steps',
      type: 'slider',
      layout: 'half',
      min: 1,
      max: 40,
      step: 1,
    },
    {
      id: 'useSearch',
      title: 'Use Web Search',
      type: 'switch',
      layout: 'half',
    },
    {
      id: 'systemPrompt',
      title: 'System Prompt (Optional)',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Add additional guidance for the agent behavior',
    },
    {
      id: 'excludeTools',
      title: 'Exclude Tools (Optional)',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Comma-separated tool names to disable, e.g. extract,observe',
    },
    {
      id: 'variables',
      title: 'Variables',
      type: 'table',
      layout: 'full',
      columns: ['Key', 'Value'],
    },
    {
      id: 'apiKey',
      title: 'Model Provider API Key',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter your API key for the selected model provider',
      password: true,
      required: true,
    },
    {
      id: 'browserbaseApiKey',
      title: 'Browserbase API Key (Optional)',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Override server Browserbase API key',
      password: true,
    },
    {
      id: 'browserbaseProjectId',
      title: 'Browserbase Project ID (Optional)',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Override server Browserbase project ID',
    },
    {
      id: 'outputSchema',
      title: 'Output Schema',
      type: 'code',
      layout: 'full',
      placeholder: 'Enter JSON Schema...',
      language: 'json',
      generationType: 'json-schema',
    },
  ],
  tools: {
    access: ['stagehand_agent'],
    config: {
      tool: () => 'stagehand_agent',
    },
  },
  inputs: {
    startUrl: { type: 'string', description: 'Starting URL for agent' },
    task: { type: 'string', description: 'Task description' },
    provider: { type: 'string', description: 'Model provider for the agent' },
    model: { type: 'string', description: 'Model name for the agent' },
    mode: { type: 'string', description: 'Agent mode: dom, cua, or hybrid' },
    maxSteps: { type: 'number', description: 'Maximum number of agent steps' },
    useSearch: { type: 'boolean', description: 'Enable web search for the agent' },
    systemPrompt: { type: 'string', description: 'Additional system prompt for the agent' },
    excludeTools: { type: 'string', description: 'Comma-separated list of tools to exclude' },
    variables: { type: 'json', description: 'Task variables' },
    apiKey: { type: 'string', description: 'Model provider API key' },
    browserbaseApiKey: {
      type: 'string',
      description: 'Optional Browserbase API key override',
    },
    browserbaseProjectId: {
      type: 'string',
      description: 'Optional Browserbase project ID override',
    },
    outputSchema: { type: 'json', description: 'Output schema' },
  },
  outputs: {
    agentResult: { type: 'json', description: 'Agent execution result' },
    structuredOutput: { type: 'json', description: 'Structured output data' },
  },
}
