import { TemporalIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'

const WORKFLOW_ID_OPS = [
  'temporal_start_workflow',
  'temporal_signal_workflow',
  'temporal_signal_with_start_workflow',
  'temporal_query_workflow',
  'temporal_describe_workflow',
  'temporal_terminate_workflow',
  'temporal_cancel_workflow',
  'temporal_reset_workflow',
  'temporal_get_workflow_history',
]

const SCHEDULE_ID_OPS = [
  'temporal_create_schedule',
  'temporal_describe_schedule',
  'temporal_update_schedule',
  'temporal_delete_schedule',
  'temporal_trigger_schedule',
  'temporal_pause_schedule',
  'temporal_unpause_schedule',
]

export const TemporalBlock: BlockConfig = {
  type: 'temporal',
  name: 'Temporal',
  description: 'Orchestrate durable Temporal workflows and schedules',
  longDescription:
    'Drive durable execution with Temporal. Start, signal, query, describe, list, terminate, cancel and reset workflow executions, and manage Temporal schedules — all via the Temporal server REST HTTP API with your namespace and connection details.',
  docsLink: '#',
  category: 'tools',
  bgColor: '#141414',
  icon: TemporalIcon,
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      layout: 'full',
      required: true,
      options: [
        { label: 'Start Workflow', id: 'temporal_start_workflow' },
        { label: 'Signal Workflow', id: 'temporal_signal_workflow' },
        { label: 'Signal With Start', id: 'temporal_signal_with_start_workflow' },
        { label: 'Query Workflow', id: 'temporal_query_workflow' },
        { label: 'Describe Workflow', id: 'temporal_describe_workflow' },
        { label: 'List Workflows', id: 'temporal_list_workflows' },
        { label: 'Count Workflows', id: 'temporal_count_workflows' },
        { label: 'Terminate Workflow', id: 'temporal_terminate_workflow' },
        { label: 'Cancel Workflow', id: 'temporal_cancel_workflow' },
        { label: 'Reset Workflow', id: 'temporal_reset_workflow' },
        { label: 'Get Workflow History', id: 'temporal_get_workflow_history' },
        { label: 'Create Schedule', id: 'temporal_create_schedule' },
        { label: 'Describe Schedule', id: 'temporal_describe_schedule' },
        { label: 'Update Schedule', id: 'temporal_update_schedule' },
        { label: 'Delete Schedule', id: 'temporal_delete_schedule' },
        { label: 'List Schedules', id: 'temporal_list_schedules' },
        { label: 'Trigger Schedule', id: 'temporal_trigger_schedule' },
        { label: 'Pause Schedule', id: 'temporal_pause_schedule' },
        { label: 'Unpause Schedule', id: 'temporal_unpause_schedule' },
        { label: 'Describe Namespace', id: 'temporal_describe_namespace' },
      ],
    },
    {
      id: 'serverUrl',
      title: 'Server URL',
      type: 'short-input',
      layout: 'full',
      placeholder: 'https://your-namespace.tmprl.cloud',
      required: true,
    },
    {
      id: 'namespace',
      title: 'Namespace',
      type: 'short-input',
      layout: 'full',
      placeholder: 'default',
      required: true,
    },
    {
      id: 'apiKey',
      title: 'API Key',
      type: 'short-input',
      layout: 'full',
      password: true,
      placeholder: 'Temporal Cloud API key (optional for self-hosted)',
    },
    {
      id: 'workflowId',
      title: 'Workflow ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'order-12345',
      condition: { field: 'operation', value: WORKFLOW_ID_OPS },
    },
    {
      id: 'runId',
      title: 'Run ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'optional run ID',
      condition: {
        field: 'operation',
        value: [
          'temporal_signal_workflow',
          'temporal_query_workflow',
          'temporal_describe_workflow',
          'temporal_terminate_workflow',
          'temporal_cancel_workflow',
          'temporal_reset_workflow',
          'temporal_get_workflow_history',
        ],
      },
    },
    {
      id: 'workflowType',
      title: 'Workflow Type',
      type: 'short-input',
      layout: 'full',
      placeholder: 'OrderWorkflow',
      condition: {
        field: 'operation',
        value: ['temporal_start_workflow', 'temporal_signal_with_start_workflow'],
      },
    },
    {
      id: 'taskQueue',
      title: 'Task Queue',
      type: 'short-input',
      layout: 'full',
      placeholder: 'orders',
      condition: {
        field: 'operation',
        value: ['temporal_start_workflow', 'temporal_signal_with_start_workflow'],
      },
    },
    {
      id: 'signalName',
      title: 'Signal Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'approve',
      condition: {
        field: 'operation',
        value: ['temporal_signal_workflow', 'temporal_signal_with_start_workflow'],
      },
    },
    {
      id: 'queryType',
      title: 'Query Type',
      type: 'short-input',
      layout: 'full',
      placeholder: 'getStatus',
      condition: { field: 'operation', value: ['temporal_query_workflow'] },
    },
    {
      id: 'input',
      title: 'Input (JSON)',
      type: 'code',
      layout: 'full',
      placeholder: '["arg1", { "key": "value" }]',
      condition: {
        field: 'operation',
        value: [
          'temporal_start_workflow',
          'temporal_signal_workflow',
          'temporal_signal_with_start_workflow',
          'temporal_query_workflow',
          'temporal_create_schedule',
        ],
      },
    },
    {
      id: 'signalInput',
      title: 'Signal Input (JSON)',
      type: 'code',
      layout: 'full',
      placeholder: '["approved"]',
      condition: { field: 'operation', value: ['temporal_signal_with_start_workflow'] },
    },
    {
      id: 'workflowTaskFinishEventId',
      title: 'Reset To Event ID',
      type: 'short-input',
      layout: 'full',
      placeholder: '4',
      condition: { field: 'operation', value: ['temporal_reset_workflow'] },
    },
    {
      id: 'reason',
      title: 'Reason',
      type: 'short-input',
      layout: 'full',
      placeholder: 'optional reason',
      condition: {
        field: 'operation',
        value: [
          'temporal_terminate_workflow',
          'temporal_cancel_workflow',
          'temporal_reset_workflow',
          'temporal_pause_schedule',
          'temporal_unpause_schedule',
        ],
      },
    },
    {
      id: 'query',
      title: 'List Filter Query',
      type: 'long-input',
      layout: 'full',
      placeholder: 'ExecutionStatus = "Running"',
      condition: {
        field: 'operation',
        value: ['temporal_list_workflows', 'temporal_count_workflows', 'temporal_list_schedules'],
      },
    },
    {
      id: 'scheduleId',
      title: 'Schedule ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'daily-report',
      condition: { field: 'operation', value: SCHEDULE_ID_OPS },
    },
    {
      id: 'cronExpression',
      title: 'Cron Expression',
      type: 'short-input',
      layout: 'full',
      placeholder: '0 12 * * *',
      condition: { field: 'operation', value: ['temporal_create_schedule'] },
    },
    {
      id: 'schedule',
      title: 'Schedule (JSON)',
      type: 'code',
      layout: 'full',
      placeholder: '{"spec": {...}, "action": {...}}',
      condition: {
        field: 'operation',
        value: ['temporal_create_schedule', 'temporal_update_schedule'],
      },
    },
    {
      id: 'overlapPolicy',
      title: 'Overlap Policy',
      type: 'short-input',
      layout: 'full',
      placeholder: 'SCHEDULE_OVERLAP_POLICY_ALLOW_ALL',
      condition: { field: 'operation', value: ['temporal_trigger_schedule'] },
    },
    {
      id: 'pageSize',
      title: 'Page Size',
      type: 'short-input',
      layout: 'half',
      placeholder: '100',
      condition: {
        field: 'operation',
        value: [
          'temporal_list_workflows',
          'temporal_get_workflow_history',
          'temporal_list_schedules',
        ],
      },
    },
    {
      id: 'nextPageToken',
      title: 'Next Page Token',
      type: 'short-input',
      layout: 'half',
      placeholder: 'pagination token',
      condition: {
        field: 'operation',
        value: [
          'temporal_list_workflows',
          'temporal_get_workflow_history',
          'temporal_list_schedules',
        ],
      },
    },
  ],
  tools: {
    access: [
      'temporal_start_workflow',
      'temporal_signal_workflow',
      'temporal_signal_with_start_workflow',
      'temporal_query_workflow',
      'temporal_describe_workflow',
      'temporal_list_workflows',
      'temporal_count_workflows',
      'temporal_terminate_workflow',
      'temporal_cancel_workflow',
      'temporal_reset_workflow',
      'temporal_get_workflow_history',
      'temporal_create_schedule',
      'temporal_describe_schedule',
      'temporal_update_schedule',
      'temporal_delete_schedule',
      'temporal_list_schedules',
      'temporal_trigger_schedule',
      'temporal_pause_schedule',
      'temporal_unpause_schedule',
      'temporal_describe_namespace',
    ],
    config: {
      tool: (params) => params.operation || 'temporal_start_workflow',
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    serverUrl: { type: 'string', description: 'Temporal server base URL' },
    namespace: { type: 'string', description: 'Temporal namespace' },
    apiKey: { type: 'string', description: 'Temporal API key (Bearer token)' },
    workflowId: { type: 'string', description: 'Workflow ID' },
    runId: { type: 'string', description: 'Run ID' },
    workflowType: { type: 'string', description: 'Registered workflow type' },
    taskQueue: { type: 'string', description: 'Task queue' },
    signalName: { type: 'string', description: 'Signal name' },
    signalInput: { type: 'json', description: 'Signal arguments' },
    queryType: { type: 'string', description: 'Query type' },
    input: { type: 'json', description: 'Workflow/signal/query arguments' },
    workflowTaskFinishEventId: { type: 'number', description: 'History event ID to reset to' },
    reason: { type: 'string', description: 'Reason note' },
    query: { type: 'string', description: 'List Filter query' },
    scheduleId: { type: 'string', description: 'Schedule ID' },
    cronExpression: { type: 'string', description: 'Cron expression' },
    schedule: { type: 'json', description: 'Full Schedule object' },
    overlapPolicy: { type: 'string', description: 'Schedule overlap policy' },
    pageSize: { type: 'number', description: 'Page size' },
    nextPageToken: { type: 'string', description: 'Pagination token' },
  },
  outputs: {
    runId: { type: 'string', description: 'Run ID' },
    workflowId: { type: 'string', description: 'Workflow ID' },
    started: { type: 'boolean', description: 'Whether a workflow was started' },
    result: { type: 'json', description: 'Query result' },
    status: { type: 'string', description: 'Workflow execution status' },
    workflowExecutionInfo: { type: 'json', description: 'Full execution info' },
    executions: { type: 'json', description: 'Listed workflow executions' },
    count: { type: 'number', description: 'Count of matching items' },
    events: { type: 'json', description: 'Workflow history events' },
    nextPageToken: { type: 'string', description: 'Pagination token' },
    schedule: { type: 'json', description: 'Schedule definition' },
    schedules: { type: 'json', description: 'Listed schedules' },
    scheduleId: { type: 'string', description: 'Schedule ID' },
    namespaceInfo: { type: 'json', description: 'Namespace info' },
  },
}
