import type { Metadata } from 'next'
import { getBrandConfig } from '@/lib/branding/branding'
import { env } from '@/lib/env'

const SITE_URL = 'https://zelaxy.in'

/**
 * Generate dynamic metadata based on brand configuration
 */
export function generateBrandedMetadata(override: Partial<Metadata> = {}): Metadata {
  const brand = getBrandConfig()
  const baseUrl = env.NEXT_PUBLIC_APP_URL || SITE_URL

  const defaultTitle = `${brand.name} — Visual AI Agent Builder & Workflow Automation`
  const defaultDescription =
    'Zelaxy is the visual operating system for AI work. Compose agents, workflows, automation, reasoning and knowledge on one canvas — then deploy to production, together, in real time. No code required.'

  return {
    title: {
      template: `%s | ${brand.name}`,
      default: defaultTitle,
    },
    description: defaultDescription,
    applicationName: brand.name,
    authors: [{ name: brand.name, url: baseUrl }],
    generator: 'Next.js',
    keywords: [
      'AI agent builder',
      'AI workflow automation',
      'visual workflow editor',
      'no-code AI agents',
      'drag and drop AI builder',
      'AI agent deployment',
      'workflow canvas',
      'AI automation platform',
      'business process automation',
      'AI agent orchestration',
      'LLM workflow builder',
      'AI pipeline builder',
      'multi-agent system',
      'agentic workflow',
      'AI tools integration',
      'workflow designer',
      'intelligent automation',
      'AI agent evaluation',
      'real-time collaboration AI',
      'open source AI builder',
      // High-intent comparison / discovery terms
      'n8n alternative',
      'Zapier alternative',
      'open source Zapier',
      'Flowise alternative',
      'Langflow alternative',
      'LangChain alternative',
      'self-hosted AI automation',
      'open source workflow automation',
      'RAG pipeline builder',
      'AI agent framework',
      'build AI agents no code',
      'MCP workflow builder',
    ],
    referrer: 'origin-when-cross-origin',
    creator: brand.name,
    publisher: brand.name,
    metadataBase: new URL(baseUrl),
    alternates: {
      canonical: '/',
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        'max-image-preview': 'large',
        'max-video-preview': -1,
        'max-snippet': -1,
      },
    },
    openGraph: {
      type: 'website',
      locale: 'en_US',
      url: baseUrl,
      title: defaultTitle,
      description: defaultDescription,
      siteName: brand.name,
      // The share image is generated by app/opengraph-image.tsx (a hero-style card),
      // so it is intentionally NOT set here — Next.js wires the generated image automatically.
    },
    twitter: {
      card: 'summary_large_image',
      title: defaultTitle,
      description: defaultDescription,
      // Image supplied by app/twitter-image.tsx (see openGraph note above).
      creator: '@zelaxy',
      site: '@zelaxy',
    },
    manifest: '/manifest.webmanifest',
    icons: {
      icon: [
        { url: '/favicon/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
        { url: '/favicon/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
        {
          url: '/favicon/favicon-192x192.png',
          sizes: '192x192',
          type: 'image/png',
        },
        {
          url: '/favicon/favicon-512x512.png',
          sizes: '512x512',
          type: 'image/png',
        },
        { url: brand.faviconUrl || '/Zelaxy.png', sizes: 'any', type: 'image/png' },
      ],
      apple: '/favicon/apple-touch-icon.png',
      shortcut: brand.faviconUrl || '/favicon/favicon.ico',
    },
    appleWebApp: {
      capable: true,
      statusBarStyle: 'default',
      title: brand.name,
    },
    formatDetection: {
      telephone: false,
    },
    category: 'technology',
    other: {
      'apple-mobile-web-app-capable': 'yes',
      'mobile-web-app-capable': 'yes',
      'msapplication-TileColor': brand.primaryColor || '#ffffff',
      'msapplication-config': '/favicon/browserconfig.xml',
    },
    ...override,
  }
}

/**
 * SoftwareApplication structured data (JSON-LD)
 */
export function generateStructuredData() {
  const brand = getBrandConfig()
  const baseUrl = env.NEXT_PUBLIC_APP_URL || SITE_URL

  return {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: brand.name,
    alternateName: 'Zelaxy AI Agent Builder',
    description:
      'Zelaxy is the visual operating system for AI work. Compose agents, workflows, automation, reasoning and knowledge on one canvas — then deploy to production, together, in real time. No code required.',
    url: baseUrl,
    applicationCategory: 'BusinessApplication',
    applicationSubCategory: 'Artificial Intelligence',
    operatingSystem: 'Web Browser',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
      category: 'SaaS',
    },
    creator: {
      '@type': 'Organization',
      name: brand.name,
      url: baseUrl,
      logo: `${baseUrl}/Zelaxy.png`,
      sameAs: ['https://github.com/manu14357/Zelaxy', 'https://x.com/zelaxy'],
    },
    featureList: [
      'Visual drag-and-drop AI agent builder with 264 blocks',
      '240+ app and tool integrations (880+ actions)',
      '21 AI providers — OpenAI, Claude, Gemini, Groq, Ollama and more',
      'Built-in RAG and vector search (pgvector)',
      'Real-time multi-user collaboration',
      'Topological execution engine with loops, parallel branches and sub-workflows',
      'Guardrails — PII detection, hallucination checks, JSON-schema validation',
      'One-click agent deployment',
      'Custom block and tool SDK (TypeScript + Python) and CLI',
      'Self-hostable open-source platform',
    ],
    screenshot: `${baseUrl}/opengraph-image`,
    softwareVersion: '1.0',
    releaseNotes: 'Initial public release',
  }
}

/**
 * Organization structured data (JSON-LD)
 */
export function generateOrganizationData() {
  const brand = getBrandConfig()
  const baseUrl = env.NEXT_PUBLIC_APP_URL || SITE_URL

  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: brand.name,
    url: baseUrl,
    logo: `${baseUrl}/Zelaxy.png`,
    description: 'Open-source AI agent builder and workflow automation platform.',
    email: brand.supportEmail,
    sameAs: ['https://github.com/manu14357/Zelaxy', 'https://x.com/zelaxy'],
  }
}

/**
 * WebSite structured data with search action (JSON-LD)
 */
export function generateWebsiteData() {
  const brand = getBrandConfig()
  const baseUrl = env.NEXT_PUBLIC_APP_URL || SITE_URL

  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: brand.name,
    url: baseUrl,
    description: 'Build, test, and deploy AI agents on a visual drag-and-drop canvas.',
    publisher: {
      '@type': 'Organization',
      name: brand.name,
      logo: `${baseUrl}/Zelaxy.png`,
    },
  }
}
