// Provider tools - handled separately
import {
  a2aCancelTaskTool,
  a2aGetAgentCardTool,
  a2aGetTaskTool,
  a2aResubscribeTool,
  a2aSendMessageTool,
  a2aSetPushNotificationTool,
} from '@/tools/a2a'
import {
  agentmailCreateDraftTool,
  agentmailForwardMessageTool,
  agentmailGetThreadTool,
  agentmailListThreadsTool,
  agentmailReplyMessageTool,
  agentmailSendMessageTool,
} from '@/tools/agentmail'
import {
  agentphoneCreateCallTool,
  agentphoneCreateNumberTool,
  agentphoneListNumbersTool,
  agentphoneReleaseNumberTool,
  agentphoneSendMessageTool,
} from '@/tools/agentphone'
import {
  agiloftCreateRecordTool,
  agiloftDeleteRecordTool,
  agiloftQueryRecordsTool,
  agiloftReadRecordTool,
  agiloftUpdateRecordTool,
} from '@/tools/agiloft'
import {
  ahrefsBacklinksTool,
  ahrefsDomainRatingTool,
  ahrefsOrganicKeywordsTool,
  ahrefsReferringDomainsTool,
  ahrefsTopPagesTool,
} from '@/tools/ahrefs'
import {
  airtableCreateRecordsTool,
  airtableGetRecordTool,
  airtableListRecordsTool,
  airtableUpdateRecordTool,
} from '@/tools/airtable'
import { airweaveSearchTool } from '@/tools/airweave'
import {
  algoliaDeleteDocumentTool,
  algoliaGetDocumentTool,
  algoliaIndexDocumentTool,
  algoliaSearchTool,
  algoliaUpdateDocumentTool,
} from '@/tools/algolia'
import {
  amplitudeExportEventsTool,
  amplitudeGetUserActivityTool,
  amplitudeIdentifyUserTool,
  amplitudeSendEventTool,
  amplitudeUserSearchTool,
} from '@/tools/amplitude'
import {
  apifyGetDatasetTool,
  apifyGetRunTool,
  apifyRunActorAsyncTool,
  apifyRunActorSyncTool,
} from '@/tools/apify'
import {
  apolloFindEmailTool,
  apolloOrganizationEnrichTool,
  apolloOrganizationSearchTool,
  apolloPeopleEnrichTool,
  apolloPeopleSearchTool,
} from '@/tools/apollo'
import { arxivGetAuthorPapersTool, arxivGetPaperTool, arxivSearchTool } from '@/tools/arxiv'
import {
  asanaAddCommentTool,
  asanaCreateTaskTool,
  asanaDeleteTaskTool,
  asanaGetProjectsTool,
  asanaGetTaskTool,
  asanaSearchTasksTool,
  asanaUpdateTaskTool,
} from '@/tools/asana'
import {
  ashbyCreateCandidateTool,
  ashbyGetCandidateTool,
  ashbyGetJobPostingsTool,
  ashbyListApplicationsTool,
  ashbyListCandidatesTool,
  ashbyUpdateCandidateTool,
} from '@/tools/ashby'
import {
  athenaGetQueryExecutionTool,
  athenaGetQueryResultsTool,
  athenaListQueryExecutionsTool,
  athenaStartQueryTool,
  athenaStopQueryTool,
} from '@/tools/athena'
import {
  attioCreateNoteTool,
  attioCreateRecordTool,
  attioDeleteRecordTool,
  attioGetRecordTool,
  attioListNotesTool,
  attioListRecordsTool,
  attioUpdateRecordTool,
} from '@/tools/attio'
import {
  azureDevOpsCreateWorkItemTool,
  azureDevOpsGetPipelineRunTool,
  azureDevOpsGetWorkItemTool,
  azureDevOpsListPipelinesTool,
  azureDevOpsQueryWorkItemsTool,
  azureDevOpsRunPipelineTool,
  azureDevOpsUpdateWorkItemTool,
} from '@/tools/azure_devops'
import {
  boxCreateFolderTool,
  boxCreateSharedLinkTool,
  boxDeleteFileTool,
  boxDownloadFileTool,
  boxGetFileInfoTool,
  boxListFolderTool,
  boxUploadFileTool,
} from '@/tools/box'
import { brandfetchGetBrandTool, brandfetchSearchTool } from '@/tools/brandfetch'
import {
  brightDataDiscoverTool,
  brightDataScrapeUrlTool,
  brightDataSerpSearchTool,
} from '@/tools/brightdata'
import { browserUseRunTaskTool } from '@/tools/browser_use'
import {
  calcomCancelBookingTool,
  calcomCreateBookingTool,
  calcomGetBookingTool,
  calcomGetSlotsTool,
  calcomListBookingsTool,
  calcomListEventTypesTool,
} from '@/tools/calcom'
import {
  calendlyCancelEventTool,
  calendlyGetCurrentUserTool,
  calendlyGetEventTypeTool,
  calendlyGetScheduledEventTool,
  calendlyListEventInviteesTool,
  calendlyListEventTypesTool,
  calendlyListScheduledEventsTool,
} from '@/tools/calendly'
import { clayPopulateTool } from '@/tools/clay'
import {
  clerkCreateUserTool,
  clerkDeleteUserTool,
  clerkGetOrganizationTool,
  clerkGetUserTool,
  clerkListOrganizationsTool,
  clerkListSessionsTool,
  clerkListUsersTool,
  clerkRevokeSessionTool,
  clerkUpdateUserTool,
} from '@/tools/clerk'
import {
  cloudflareCreateDnsRecordTool,
  cloudflareDeleteDnsRecordTool,
  cloudflareGetZoneTool,
  cloudflareListDnsRecordsTool,
  cloudflareListZonesTool,
  cloudflarePurgeCacheTool,
  cloudflareUpdateDnsRecordTool,
} from '@/tools/cloudflare'
import {
  cloudformationDescribeStackEventsTool,
  cloudformationDescribeStacksTool,
  cloudformationDetectStackDriftTool,
  cloudformationGetTemplateTool,
  cloudformationListStackResourcesTool,
  cloudformationValidateTemplateTool,
} from '@/tools/cloudformation'
import {
  cloudwatchDescribeAlarmsTool,
  cloudwatchDescribeLogGroupsTool,
  cloudwatchGetLogEventsTool,
  cloudwatchGetMetricStatisticsTool,
  cloudwatchListMetricsTool,
  cloudwatchPutMetricDataTool,
  cloudwatchQueryLogsTool,
} from '@/tools/cloudwatch'
import { confluenceRetrieveTool, confluenceUpdateTool } from '@/tools/confluence'
import {
  crowdstrikeGetSensorAggregatesTool,
  crowdstrikeGetSensorDetailsTool,
  crowdstrikeQuerySensorsTool,
} from '@/tools/crowdstrike'
import {
  cursorAddFollowupTool,
  cursorGetAgentTool,
  cursorGetConversationTool,
  cursorLaunchAgentTool,
  cursorListAgentsTool,
  cursorStopAgentTool,
} from '@/tools/cursor'
import {
  dagsterGetRunLogsTool,
  dagsterGetRunTool,
  dagsterLaunchRunTool,
  dagsterListJobsTool,
  dagsterListRunsTool,
  dagsterListSchedulesTool,
  dagsterTerminateRunTool,
} from '@/tools/dagster'
import {
  databricksExecuteSqlTool,
  databricksGetRunStatusTool,
  databricksListCatalogsTool,
  databricksListClustersTool,
  databricksListJobsTool,
  databricksRunJobTool,
} from '@/tools/databricks'
import {
  datadogCreateIncidentTool,
  datadogListDashboardsTool,
  datadogListIncidentsTool,
  datadogListMonitorsTool,
  datadogQueryLogsTool,
  datadogQueryMetricsTool,
} from '@/tools/datadog'
import { delayTool } from '@/tools/delay'
import {
  devinAddSecretTool,
  devinCreateSessionTool,
  devinDeleteSecretTool,
  devinGetSessionTool,
  devinGetSnapshotTool,
  devinListSessionsTool,
  devinSendMessageTool,
} from '@/tools/devin'
import {
  discordGetMessagesTool,
  discordGetServerTool,
  discordGetUserTool,
  discordSendMessageTool,
} from '@/tools/discord'
import {
  docusignCreateEnvelopeTool,
  docusignGetEnvelopeTool,
  docusignGetSigningUrlTool,
  docusignListEnvelopesTool,
  docusignSendEnvelopeTool,
  docusignVoidEnvelopeTool,
} from '@/tools/docusign'
import {
  dropboxCreateFolderTool,
  dropboxCreateSharedLinkTool,
  dropboxDeleteFileTool,
  dropboxDownloadFileTool,
  dropboxGetFileMetadataTool,
  dropboxListFolderTool,
  dropboxSearchFilesTool,
  dropboxUploadFileTool,
} from '@/tools/dropbox'
import { dspyRunTool } from '@/tools/dspy'
import {
  dubCreateLinkTool,
  dubDeleteLinkTool,
  dubGetAnalyticsTool,
  dubGetLinkTool,
  dubListLinksTool,
  dubUpdateLinkTool,
} from '@/tools/dub'
import {
  duckduckgoImagesSearchTool,
  duckduckgoNewsSearchTool,
  duckduckgoTextSearchTool,
} from '@/tools/duckduckgo'
import {
  dynamodbBatchWriteTool,
  dynamodbDeleteItemTool,
  dynamodbGetItemTool,
  dynamodbPutItemTool,
  dynamodbQueryTool,
  dynamodbScanTool,
  dynamodbUpdateItemTool,
} from '@/tools/dynamodb'
import {
  elasticsearchBulkTool,
  elasticsearchDeleteTool,
  elasticsearchGetTool,
  elasticsearchIndexTool,
  elasticsearchListIndicesTool,
  elasticsearchSearchTool,
} from '@/tools/elasticsearch'
import { elevenLabsTtsTool } from '@/tools/elevenlabs'
import {
  emailbisonBulkFindTool,
  emailbisonDomainSearchTool,
  emailbisonFindEmailTool,
  emailbisonVerifyEmailTool,
} from '@/tools/emailbison'
import {
  enrichCompanyLookupTool,
  enrichEmailToProfileTool,
  enrichFindEmailTool,
  enrichPhoneFinderTool,
  enrichSearchPeopleTool,
  enrichVerifyEmailTool,
} from '@/tools/enrich'
import {
  evernoteCreateNoteTool,
  evernoteDeleteNoteTool,
  evernoteGetNoteTool,
  evernoteListNotebooksTool,
  evernoteSearchNotesTool,
  evernoteUpdateNoteTool,
} from '@/tools/evernote'
import {
  exaAnswerTool,
  exaFindSimilarLinksTool,
  exaGetContentsTool,
  exaResearchTool,
  exaSearchTool,
} from '@/tools/exa'
import {
  fathomGetSummaryTool,
  fathomGetTranscriptTool,
  fathomListMeetingsTool,
  fathomListTeamMembersTool,
  fathomListTeamsTool,
} from '@/tools/fathom'
import { fileParseTool } from '@/tools/file'
import { crawlTool, scrapeTool, searchTool } from '@/tools/firecrawl'
import { functionExecuteTool } from '@/tools/function'
import {
  githubCommentTool,
  githubLatestCommitTool,
  githubPrTool,
  githubRepoInfoTool,
} from '@/tools/github'
import { gmailDraftTool, gmailReadTool, gmailSearchTool, gmailSendTool } from '@/tools/gmail'
import { searchTool as googleSearchTool } from '@/tools/google'
import {
  googleCalendarCreateTool,
  googleCalendarGetTool,
  googleCalendarInviteTool,
  googleCalendarListTool,
  googleCalendarQuickAddTool,
} from '@/tools/google_calendar'
import { googleDocsCreateTool, googleDocsReadTool, googleDocsWriteTool } from '@/tools/google_docs'
import {
  googleDriveCreateFolderTool,
  googleDriveGetContentTool,
  googleDriveListTool,
  googleDriveUploadTool,
} from '@/tools/google_drive'
import {
  googleSheetsAppendTool,
  googleSheetsReadTool,
  googleSheetsUpdateTool,
  googleSheetsWriteTool,
} from '@/tools/google_sheets'
import { guardrailsTool } from '@/tools/guardrails'
import { requestTool as httpRequest } from '@/tools/http'
import { huggingfaceChatTool } from '@/tools/huggingface'
import {
  hunterCompaniesFindTool,
  hunterDiscoverTool,
  hunterDomainSearchTool,
  hunterEmailCountTool,
  hunterEmailFinderTool,
  hunterEmailVerifierTool,
} from '@/tools/hunter'
import {
  imageSearchCatalogTool,
  imageSearchIngestTool,
  imageSearchStatusTool,
  imageSearchTool,
} from '@/tools/image_search'
import { readUrlTool } from '@/tools/jina'
import { jiraBulkRetrieveTool, jiraRetrieveTool, jiraUpdateTool, jiraWriteTool } from '@/tools/jira'
import {
  knowledgeCreateDocumentTool,
  knowledgeSearchTool,
  knowledgeUploadChunkTool,
} from '@/tools/knowledge'
import { linearCreateIssueTool, linearReadIssuesTool } from '@/tools/linear'
import {
  linkedinCreatePostTool,
  linkedinDeletePostTool,
  linkedinGetCompanyTool,
  linkedinGetProfileTool,
} from '@/tools/linkedin'
import { linkupSearchTool } from '@/tools/linkup'
import {
  mcpConnectTool,
  mcpCreateServerTool,
  mcpDiscoverToolsTool,
  mcpExecuteToolTool,
} from '@/tools/mcp'
import { mem0AddMemoriesTool, mem0GetMemoriesTool, mem0SearchMemoriesTool } from '@/tools/mem0'
import { memoryAddTool, memoryDeleteTool, memoryGetAllTool, memoryGetTool } from '@/tools/memory'
import {
  microsoftExcelReadTool,
  microsoftExcelTableAddTool,
  microsoftExcelUpdateTool,
  microsoftExcelWriteTool,
} from '@/tools/microsoft_excel'
import {
  microsoftPlannerCreateTaskTool,
  microsoftPlannerReadTaskTool,
} from '@/tools/microsoft_planner'
import {
  microsoftTeamsReadChannelTool,
  microsoftTeamsReadChatTool,
  microsoftTeamsWriteChannelTool,
  microsoftTeamsWriteChatTool,
} from '@/tools/microsoft_teams'
import { mistralParserTool } from '@/tools/mistral'
import { mssqlTool } from '@/tools/mssql'
import { mysqlTool } from '@/tools/mysql'
import {
  notionCreateDatabaseTool,
  notionCreatePageTool,
  notionQueryDatabaseTool,
  notionReadDatabaseTool,
  notionReadTool,
  notionSearchTool,
  notionWriteTool,
} from '@/tools/notion'
import { onedriveCreateFolderTool, onedriveListTool, onedriveUploadTool } from '@/tools/onedrive'
import { imageTool, embeddingsTool as openAIEmbeddings } from '@/tools/openai'
import { outlookDraftTool, outlookReadTool, outlookSendTool } from '@/tools/outlook'
import { perplexityChatTool } from '@/tools/perplexity'
import {
  pineconeFetchTool,
  pineconeGenerateEmbeddingsTool,
  pineconeSearchTextTool,
  pineconeSearchVectorTool,
  pineconeUpsertTextTool,
} from '@/tools/pinecone'
import { postgresqlTool } from '@/tools/postgresql'
import { qdrantFetchTool, qdrantSearchTool, qdrantUpsertTool } from '@/tools/qdrant'
import { redditGetCommentsTool, redditGetPostsTool, redditHotPostsTool } from '@/tools/reddit'
import { resendBatchTool, resendCancelTool, resendGetTool, resendSendTool } from '@/tools/resend'
import { s3GetObjectTool } from '@/tools/s3'
import { searchTool as serperSearch } from '@/tools/serper'
import {
  sharepointCreatePageTool,
  sharepointListSitesTool,
  sharepointReadPageTool,
} from '@/tools/sharepoint'
import { slackCanvasTool, slackMessageReaderTool, slackMessageTool } from '@/tools/slack'
import { smtpSendTool } from '@/tools/smtp'
import { snowflakeTool } from '@/tools/snowflake'
import { stagehandAgentTool, stagehandExtractTool } from '@/tools/stagehand'
import {
  supabaseDeleteTool,
  supabaseGetRowTool,
  supabaseInsertTool,
  supabaseQueryTool,
  supabaseUpdateTool,
} from '@/tools/supabase'
import { tavilyExtractTool, tavilySearchTool } from '@/tools/tavily'
import { telegramMessageTool } from '@/tools/telegram'
import { thinkingTool } from '@/tools/thinking'
import { sendSMSTool } from '@/tools/twilio'
import { typeformFilesTool, typeformInsightsTool, typeformResponsesTool } from '@/tools/typeform'
import type { ToolConfig } from '@/tools/types'
import { visionTool } from '@/tools/vision'
import {
  wealthboxReadContactTool,
  wealthboxReadNoteTool,
  wealthboxReadTaskTool,
  wealthboxWriteContactTool,
  wealthboxWriteNoteTool,
  wealthboxWriteTaskTool,
} from '@/tools/wealthbox'
import { whatsappSendMessageTool } from '@/tools/whatsapp'
import {
  wikipediaPageContentTool,
  wikipediaPageSummaryTool,
  wikipediaRandomPageTool,
  wikipediaSearchTool,
} from '@/tools/wikipedia'
import { workflowExecutorTool } from '@/tools/workflow'
import { xReadTool, xSearchTool, xUserTool, xWriteTool } from '@/tools/x'
import { youtubeSearchTool } from '@/tools/youtube'

// Registry of all available tools
export const tools: Record<string, ToolConfig> = {
  arxiv_search: arxivSearchTool,
  arxiv_get_paper: arxivGetPaperTool,
  arxiv_get_author_papers: arxivGetAuthorPapersTool,
  browser_use_run_task: browserUseRunTaskTool,
  openai_embeddings: openAIEmbeddings,
  http_request: httpRequest,
  huggingface_chat: huggingfaceChatTool,
  function_execute: functionExecuteTool,
  guardrails_validate: guardrailsTool,
  vision_tool: visionTool,
  file_parser: fileParseTool,
  firecrawl_scrape: scrapeTool,
  firecrawl_search: searchTool,
  firecrawl_crawl: crawlTool,
  google_search: googleSearchTool,
  jina_read_url: readUrlTool,
  linkup_search: linkupSearchTool,
  jira_retrieve: jiraRetrieveTool,
  jira_update: jiraUpdateTool,
  jira_write: jiraWriteTool,
  jira_bulk_read: jiraBulkRetrieveTool,
  slack_message: slackMessageTool,
  slack_message_reader: slackMessageReaderTool,
  slack_canvas: slackCanvasTool,
  smtp_send: smtpSendTool,
  snowflake_connector: snowflakeTool,
  github_repo_info: githubRepoInfoTool,
  github_latest_commit: githubLatestCommitTool,
  serper_search: serperSearch,
  tavily_search: tavilySearchTool,
  tavily_extract: tavilyExtractTool,
  supabase_query: supabaseQueryTool,
  supabase_insert: supabaseInsertTool,
  supabase_get_row: supabaseGetRowTool,
  supabase_update: supabaseUpdateTool,
  supabase_delete: supabaseDeleteTool,
  typeform_responses: typeformResponsesTool,
  typeform_files: typeformFilesTool,
  typeform_insights: typeformInsightsTool,
  youtube_search: youtubeSearchTool,
  notion_read: notionReadTool,
  notion_read_database: notionReadDatabaseTool,
  notion_write: notionWriteTool,
  notion_create_page: notionCreatePageTool,
  notion_query_database: notionQueryDatabaseTool,
  notion_search: notionSearchTool,
  notion_create_database: notionCreateDatabaseTool,
  gmail_send: gmailSendTool,
  gmail_read: gmailReadTool,
  gmail_search: gmailSearchTool,
  gmail_draft: gmailDraftTool,
  whatsapp_send_message: whatsappSendMessageTool,
  x_write: xWriteTool,
  x_read: xReadTool,
  x_search: xSearchTool,
  x_user: xUserTool,
  linkedin_create_post: linkedinCreatePostTool,
  linkedin_get_profile: linkedinGetProfileTool,
  linkedin_get_company: linkedinGetCompanyTool,
  linkedin_delete_post: linkedinDeletePostTool,
  pinecone_fetch: pineconeFetchTool,
  pinecone_generate_embeddings: pineconeGenerateEmbeddingsTool,
  pinecone_search_text: pineconeSearchTextTool,
  pinecone_search_vector: pineconeSearchVectorTool,
  pinecone_upsert_text: pineconeUpsertTextTool,
  github_pr: githubPrTool,
  github_comment: githubCommentTool,
  exa_search: exaSearchTool,
  exa_get_contents: exaGetContentsTool,
  exa_find_similar_links: exaFindSimilarLinksTool,
  exa_answer: exaAnswerTool,
  exa_research: exaResearchTool,
  reddit_hot_posts: redditHotPostsTool,
  reddit_get_posts: redditGetPostsTool,
  reddit_get_comments: redditGetCommentsTool,
  resend_send: resendSendTool,
  resend_batch: resendBatchTool,
  resend_get: resendGetTool,
  resend_cancel: resendCancelTool,
  google_drive_get_content: googleDriveGetContentTool,
  google_drive_list: googleDriveListTool,
  google_drive_upload: googleDriveUploadTool,
  google_drive_create_folder: googleDriveCreateFolderTool,
  google_docs_read: googleDocsReadTool,
  google_docs_write: googleDocsWriteTool,
  google_docs_create: googleDocsCreateTool,
  google_sheets_read: googleSheetsReadTool,
  google_sheets_write: googleSheetsWriteTool,
  google_sheets_update: googleSheetsUpdateTool,
  google_sheets_append: googleSheetsAppendTool,
  perplexity_chat: perplexityChatTool,
  confluence_retrieve: confluenceRetrieveTool,
  confluence_update: confluenceUpdateTool,
  twilio_send_sms: sendSMSTool,
  airtable_create_records: airtableCreateRecordsTool,
  airtable_get_record: airtableGetRecordTool,
  airtable_list_records: airtableListRecordsTool,
  airtable_update_record: airtableUpdateRecordTool,
  mistral_parser: mistralParserTool,
  thinking_tool: thinkingTool,
  stagehand_extract: stagehandExtractTool,
  stagehand_agent: stagehandAgentTool,
  mem0_add_memories: mem0AddMemoriesTool,
  mem0_search_memories: mem0SearchMemoriesTool,
  mem0_get_memories: mem0GetMemoriesTool,
  memory_add: memoryAddTool,
  memory_get: memoryGetTool,
  memory_get_all: memoryGetAllTool,
  memory_delete: memoryDeleteTool,
  knowledge_search: knowledgeSearchTool,
  knowledge_upload_chunk: knowledgeUploadChunkTool,
  knowledge_create_document: knowledgeCreateDocumentTool,
  mssql_database: mssqlTool,
  mysql_database: mysqlTool,
  postgresql_database: postgresqlTool,
  elevenlabs_tts: elevenLabsTtsTool,
  s3_get_object: s3GetObjectTool,
  telegram_message: telegramMessageTool,
  clay_populate: clayPopulateTool,
  delay_wait: delayTool,
  discord_send_message: discordSendMessageTool,
  discord_get_messages: discordGetMessagesTool,
  discord_get_server: discordGetServerTool,
  discord_get_user: discordGetUserTool,
  openai_image: imageTool,
  microsoft_teams_read_chat: microsoftTeamsReadChatTool,
  microsoft_teams_write_chat: microsoftTeamsWriteChatTool,
  microsoft_teams_read_channel: microsoftTeamsReadChannelTool,
  microsoft_teams_write_channel: microsoftTeamsWriteChannelTool,
  outlook_read: outlookReadTool,
  outlook_send: outlookSendTool,
  outlook_draft: outlookDraftTool,
  linear_read_issues: linearReadIssuesTool,
  linear_create_issue: linearCreateIssueTool,
  onedrive_create_folder: onedriveCreateFolderTool,
  onedrive_list: onedriveListTool,
  onedrive_upload: onedriveUploadTool,
  microsoft_excel_read: microsoftExcelReadTool,
  microsoft_excel_write: microsoftExcelWriteTool,
  microsoft_excel_update: microsoftExcelUpdateTool,
  microsoft_excel_table_add: microsoftExcelTableAddTool,
  microsoft_planner_create_task: microsoftPlannerCreateTaskTool,
  microsoft_planner_read_task: microsoftPlannerReadTaskTool,
  google_calendar_create: googleCalendarCreateTool,
  google_calendar_get: googleCalendarGetTool,
  google_calendar_list: googleCalendarListTool,
  google_calendar_quick_add: googleCalendarQuickAddTool,
  google_calendar_invite: googleCalendarInviteTool,
  workflow_executor: workflowExecutorTool,
  wealthbox_read_contact: wealthboxReadContactTool,
  wealthbox_write_contact: wealthboxWriteContactTool,
  wealthbox_read_task: wealthboxReadTaskTool,
  wealthbox_write_task: wealthboxWriteTaskTool,
  wealthbox_read_note: wealthboxReadNoteTool,
  wealthbox_write_note: wealthboxWriteNoteTool,
  wikipedia_summary: wikipediaPageSummaryTool,
  wikipedia_search: wikipediaSearchTool,
  wikipedia_content: wikipediaPageContentTool,
  wikipedia_random: wikipediaRandomPageTool,
  qdrant_fetch_points: qdrantFetchTool,
  qdrant_search_vector: qdrantSearchTool,
  qdrant_upsert_points: qdrantUpsertTool,
  hunter_discover: hunterDiscoverTool,
  hunter_domain_search: hunterDomainSearchTool,
  hunter_email_finder: hunterEmailFinderTool,
  hunter_email_verifier: hunterEmailVerifierTool,
  hunter_companies_find: hunterCompaniesFindTool,
  hunter_email_count: hunterEmailCountTool,
  image_search_catalog: imageSearchCatalogTool,
  image_search_ingest: imageSearchIngestTool,
  image_search_search: imageSearchTool,
  image_search_status: imageSearchStatusTool,
  sharepoint_create_page: sharepointCreatePageTool,
  sharepoint_read_page: sharepointReadPageTool,
  sharepoint_list_sites: sharepointListSitesTool,
  mcp_connect: mcpConnectTool,
  mcp_create_server: mcpCreateServerTool,
  mcp_discover_tools: mcpDiscoverToolsTool,
  mcp_execute_tool: mcpExecuteToolTool,
  // New tool integrations
  a2a_send_message: a2aSendMessageTool,
  a2a_get_task: a2aGetTaskTool,
  a2a_cancel_task: a2aCancelTaskTool,
  a2a_get_agent_card: a2aGetAgentCardTool,
  a2a_resubscribe: a2aResubscribeTool,
  a2a_set_push_notification: a2aSetPushNotificationTool,
  agentmail_send_message: agentmailSendMessageTool,
  agentmail_reply_message: agentmailReplyMessageTool,
  agentmail_forward_message: agentmailForwardMessageTool,
  agentmail_list_threads: agentmailListThreadsTool,
  agentmail_get_thread: agentmailGetThreadTool,
  agentmail_create_draft: agentmailCreateDraftTool,
  agentphone_create_number: agentphoneCreateNumberTool,
  agentphone_list_numbers: agentphoneListNumbersTool,
  agentphone_release_number: agentphoneReleaseNumberTool,
  agentphone_send_message: agentphoneSendMessageTool,
  agentphone_create_call: agentphoneCreateCallTool,
  agiloft_create_record: agiloftCreateRecordTool,
  agiloft_read_record: agiloftReadRecordTool,
  agiloft_update_record: agiloftUpdateRecordTool,
  agiloft_delete_record: agiloftDeleteRecordTool,
  agiloft_query_records: agiloftQueryRecordsTool,
  ahrefs_domain_rating: ahrefsDomainRatingTool,
  ahrefs_backlinks: ahrefsBacklinksTool,
  ahrefs_organic_keywords: ahrefsOrganicKeywordsTool,
  ahrefs_top_pages: ahrefsTopPagesTool,
  ahrefs_referring_domains: ahrefsReferringDomainsTool,
  airweave_search: airweaveSearchTool,
  algolia_search: algoliaSearchTool,
  algolia_index_document: algoliaIndexDocumentTool,
  algolia_update_document: algoliaUpdateDocumentTool,
  algolia_delete_document: algoliaDeleteDocumentTool,
  algolia_get_document: algoliaGetDocumentTool,
  amplitude_send_event: amplitudeSendEventTool,
  amplitude_identify_user: amplitudeIdentifyUserTool,
  amplitude_user_search: amplitudeUserSearchTool,
  amplitude_get_user_activity: amplitudeGetUserActivityTool,
  amplitude_export_events: amplitudeExportEventsTool,
  apify_run_actor_sync: apifyRunActorSyncTool,
  apify_run_actor_async: apifyRunActorAsyncTool,
  apify_get_run: apifyGetRunTool,
  apify_get_dataset: apifyGetDatasetTool,
  apollo_people_search: apolloPeopleSearchTool,
  apollo_people_enrich: apolloPeopleEnrichTool,
  apollo_organization_search: apolloOrganizationSearchTool,
  apollo_organization_enrich: apolloOrganizationEnrichTool,
  apollo_find_email: apolloFindEmailTool,
  asana_get_task: asanaGetTaskTool,
  asana_create_task: asanaCreateTaskTool,
  asana_update_task: asanaUpdateTaskTool,
  asana_delete_task: asanaDeleteTaskTool,
  asana_get_projects: asanaGetProjectsTool,
  asana_search_tasks: asanaSearchTasksTool,
  asana_add_comment: asanaAddCommentTool,
  ashby_list_candidates: ashbyListCandidatesTool,
  ashby_get_candidate: ashbyGetCandidateTool,
  ashby_create_candidate: ashbyCreateCandidateTool,
  ashby_update_candidate: ashbyUpdateCandidateTool,
  ashby_list_applications: ashbyListApplicationsTool,
  ashby_get_job_postings: ashbyGetJobPostingsTool,
  athena_start_query: athenaStartQueryTool,
  athena_get_query_results: athenaGetQueryResultsTool,
  athena_get_query_execution: athenaGetQueryExecutionTool,
  athena_stop_query: athenaStopQueryTool,
  athena_list_query_executions: athenaListQueryExecutionsTool,
  attio_list_records: attioListRecordsTool,
  attio_get_record: attioGetRecordTool,
  attio_create_record: attioCreateRecordTool,
  attio_update_record: attioUpdateRecordTool,
  attio_delete_record: attioDeleteRecordTool,
  attio_create_note: attioCreateNoteTool,
  attio_list_notes: attioListNotesTool,
  azure_devops_list_pipelines: azureDevOpsListPipelinesTool,
  azure_devops_run_pipeline: azureDevOpsRunPipelineTool,
  azure_devops_get_pipeline_run: azureDevOpsGetPipelineRunTool,
  azure_devops_query_work_items: azureDevOpsQueryWorkItemsTool,
  azure_devops_get_work_item: azureDevOpsGetWorkItemTool,
  azure_devops_create_work_item: azureDevOpsCreateWorkItemTool,
  azure_devops_update_work_item: azureDevOpsUpdateWorkItemTool,
  box_upload_file: boxUploadFileTool,
  box_download_file: boxDownloadFileTool,
  box_list_folder: boxListFolderTool,
  box_create_folder: boxCreateFolderTool,
  box_delete_file: boxDeleteFileTool,
  box_get_file_info: boxGetFileInfoTool,
  box_create_shared_link: boxCreateSharedLinkTool,
  brandfetch_get_brand: brandfetchGetBrandTool,
  brandfetch_search: brandfetchSearchTool,
  brightdata_scrape_url: brightDataScrapeUrlTool,
  brightdata_serp_search: brightDataSerpSearchTool,
  brightdata_discover: brightDataDiscoverTool,
  calcom_list_bookings: calcomListBookingsTool,
  calcom_create_booking: calcomCreateBookingTool,
  calcom_get_booking: calcomGetBookingTool,
  calcom_cancel_booking: calcomCancelBookingTool,
  calcom_get_slots: calcomGetSlotsTool,
  calcom_list_event_types: calcomListEventTypesTool,
  calendly_get_current_user: calendlyGetCurrentUserTool,
  calendly_list_event_types: calendlyListEventTypesTool,
  calendly_get_event_type: calendlyGetEventTypeTool,
  calendly_list_scheduled_events: calendlyListScheduledEventsTool,
  calendly_get_scheduled_event: calendlyGetScheduledEventTool,
  calendly_list_event_invitees: calendlyListEventInviteesTool,
  calendly_cancel_event: calendlyCancelEventTool,
  clerk_list_users: clerkListUsersTool,
  clerk_get_user: clerkGetUserTool,
  clerk_create_user: clerkCreateUserTool,
  clerk_update_user: clerkUpdateUserTool,
  clerk_delete_user: clerkDeleteUserTool,
  clerk_list_organizations: clerkListOrganizationsTool,
  clerk_get_organization: clerkGetOrganizationTool,
  clerk_list_sessions: clerkListSessionsTool,
  clerk_revoke_session: clerkRevokeSessionTool,
  cloudflare_list_zones: cloudflareListZonesTool,
  cloudflare_get_zone: cloudflareGetZoneTool,
  cloudflare_list_dns_records: cloudflareListDnsRecordsTool,
  cloudflare_create_dns_record: cloudflareCreateDnsRecordTool,
  cloudflare_update_dns_record: cloudflareUpdateDnsRecordTool,
  cloudflare_delete_dns_record: cloudflareDeleteDnsRecordTool,
  cloudflare_purge_cache: cloudflarePurgeCacheTool,
  cloudformation_describe_stacks: cloudformationDescribeStacksTool,
  cloudformation_list_stack_resources: cloudformationListStackResourcesTool,
  cloudformation_describe_stack_events: cloudformationDescribeStackEventsTool,
  cloudformation_detect_stack_drift: cloudformationDetectStackDriftTool,
  cloudformation_get_template: cloudformationGetTemplateTool,
  cloudformation_validate_template: cloudformationValidateTemplateTool,
  cloudwatch_query_logs: cloudwatchQueryLogsTool,
  cloudwatch_describe_log_groups: cloudwatchDescribeLogGroupsTool,
  cloudwatch_get_log_events: cloudwatchGetLogEventsTool,
  cloudwatch_list_metrics: cloudwatchListMetricsTool,
  cloudwatch_get_metric_statistics: cloudwatchGetMetricStatisticsTool,
  cloudwatch_put_metric_data: cloudwatchPutMetricDataTool,
  cloudwatch_describe_alarms: cloudwatchDescribeAlarmsTool,
  crowdstrike_query_sensors: crowdstrikeQuerySensorsTool,
  crowdstrike_get_sensor_details: crowdstrikeGetSensorDetailsTool,
  crowdstrike_get_sensor_aggregates: crowdstrikeGetSensorAggregatesTool,
  cursor_launch_agent: cursorLaunchAgentTool,
  cursor_add_followup: cursorAddFollowupTool,
  cursor_get_agent: cursorGetAgentTool,
  cursor_get_conversation: cursorGetConversationTool,
  cursor_list_agents: cursorListAgentsTool,
  cursor_stop_agent: cursorStopAgentTool,
  dagster_launch_run: dagsterLaunchRunTool,
  dagster_get_run: dagsterGetRunTool,
  dagster_get_run_logs: dagsterGetRunLogsTool,
  dagster_list_runs: dagsterListRunsTool,
  dagster_terminate_run: dagsterTerminateRunTool,
  dagster_list_jobs: dagsterListJobsTool,
  dagster_list_schedules: dagsterListSchedulesTool,
  databricks_execute_sql: databricksExecuteSqlTool,
  databricks_list_clusters: databricksListClustersTool,
  databricks_list_jobs: databricksListJobsTool,
  databricks_run_job: databricksRunJobTool,
  databricks_get_run_status: databricksGetRunStatusTool,
  databricks_list_catalogs: databricksListCatalogsTool,
  datadog_query_metrics: datadogQueryMetricsTool,
  datadog_query_logs: datadogQueryLogsTool,
  datadog_list_monitors: datadogListMonitorsTool,
  datadog_create_incident: datadogCreateIncidentTool,
  datadog_list_incidents: datadogListIncidentsTool,
  datadog_list_dashboards: datadogListDashboardsTool,
  devin_create_session: devinCreateSessionTool,
  devin_get_session: devinGetSessionTool,
  devin_list_sessions: devinListSessionsTool,
  devin_send_message: devinSendMessageTool,
  devin_add_secret: devinAddSecretTool,
  devin_delete_secret: devinDeleteSecretTool,
  devin_get_snapshot: devinGetSnapshotTool,
  docusign_create_envelope: docusignCreateEnvelopeTool,
  docusign_get_envelope: docusignGetEnvelopeTool,
  docusign_list_envelopes: docusignListEnvelopesTool,
  docusign_send_envelope: docusignSendEnvelopeTool,
  docusign_get_signing_url: docusignGetSigningUrlTool,
  docusign_void_envelope: docusignVoidEnvelopeTool,
  dropbox_upload_file: dropboxUploadFileTool,
  dropbox_download_file: dropboxDownloadFileTool,
  dropbox_list_folder: dropboxListFolderTool,
  dropbox_create_folder: dropboxCreateFolderTool,
  dropbox_delete_file: dropboxDeleteFileTool,
  dropbox_get_file_metadata: dropboxGetFileMetadataTool,
  dropbox_create_shared_link: dropboxCreateSharedLinkTool,
  dropbox_search_files: dropboxSearchFilesTool,
  dspy_run: dspyRunTool,
  dub_create_link: dubCreateLinkTool,
  dub_get_link: dubGetLinkTool,
  dub_update_link: dubUpdateLinkTool,
  dub_delete_link: dubDeleteLinkTool,
  dub_list_links: dubListLinksTool,
  dub_get_analytics: dubGetAnalyticsTool,
  duckduckgo_text_search: duckduckgoTextSearchTool,
  duckduckgo_news_search: duckduckgoNewsSearchTool,
  duckduckgo_images_search: duckduckgoImagesSearchTool,
  dynamodb_get_item: dynamodbGetItemTool,
  dynamodb_put_item: dynamodbPutItemTool,
  dynamodb_update_item: dynamodbUpdateItemTool,
  dynamodb_delete_item: dynamodbDeleteItemTool,
  dynamodb_query: dynamodbQueryTool,
  dynamodb_scan: dynamodbScanTool,
  dynamodb_batch_write: dynamodbBatchWriteTool,
  elasticsearch_search: elasticsearchSearchTool,
  elasticsearch_index_document: elasticsearchIndexTool,
  elasticsearch_get: elasticsearchGetTool,
  elasticsearch_delete: elasticsearchDeleteTool,
  elasticsearch_bulk: elasticsearchBulkTool,
  elasticsearch_list_indices: elasticsearchListIndicesTool,
  emailbison_find_email: emailbisonFindEmailTool,
  emailbison_verify_email: emailbisonVerifyEmailTool,
  emailbison_bulk_find: emailbisonBulkFindTool,
  emailbison_domain_search: emailbisonDomainSearchTool,
  enrich_email_to_profile: enrichEmailToProfileTool,
  enrich_find_email: enrichFindEmailTool,
  enrich_verify_email: enrichVerifyEmailTool,
  enrich_company_lookup: enrichCompanyLookupTool,
  enrich_search_people: enrichSearchPeopleTool,
  enrich_phone_finder: enrichPhoneFinderTool,
  evernote_create_note: evernoteCreateNoteTool,
  evernote_get_note: evernoteGetNoteTool,
  evernote_update_note: evernoteUpdateNoteTool,
  evernote_delete_note: evernoteDeleteNoteTool,
  evernote_search_notes: evernoteSearchNotesTool,
  evernote_list_notebooks: evernoteListNotebooksTool,
  fathom_list_meetings: fathomListMeetingsTool,
  fathom_get_summary: fathomGetSummaryTool,
  fathom_get_transcript: fathomGetTranscriptTool,
  fathom_list_team_members: fathomListTeamMembersTool,
  fathom_list_teams: fathomListTeamsTool,
  // Provider chat tools
  // Provider chat tools - handled separately in agent blocks
}
